// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ClockifyClient.V1.Workspaces.Item.Users
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetMembershipsQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "ALL")]
        #pragma warning disable CS1591
        ALL,
        #pragma warning restore CS1591
        [EnumMember(Value = "NONE")]
        #pragma warning disable CS1591
        NONE,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKSPACE")]
        #pragma warning disable CS1591
        WORKSPACE,
        #pragma warning restore CS1591
        [EnumMember(Value = "PROJECT")]
        #pragma warning disable CS1591
        PROJECT,
        #pragma warning restore CS1591
        [EnumMember(Value = "USERGROUP")]
        #pragma warning disable CS1591
        USERGROUP,
        #pragma warning restore CS1591
    }
}
