// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ClockifyClient.Models
{
    /// <summary>
    /// Provide automatic accrual settings.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AutomaticAccrualRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Represents amount of automatic accrual.</summary>
        public double? Amount { get; set; }
        /// <summary>Represents automatic accrual period.</summary>
        public global::ClockifyClient.Models.AutomaticAccrualRequest_period? Period { get; set; }
        /// <summary>Represents automatic accrual time unit.</summary>
        public global::ClockifyClient.Models.AutomaticAccrualRequest_timeUnit? TimeUnit { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::ClockifyClient.Models.AutomaticAccrualRequest"/> and sets the default values.
        /// </summary>
        public AutomaticAccrualRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ClockifyClient.Models.AutomaticAccrualRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ClockifyClient.Models.AutomaticAccrualRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ClockifyClient.Models.AutomaticAccrualRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "amount", n => { Amount = n.GetDoubleValue(); } },
                { "period", n => { Period = n.GetEnumValue<global::ClockifyClient.Models.AutomaticAccrualRequest_period>(); } },
                { "timeUnit", n => { TimeUnit = n.GetEnumValue<global::ClockifyClient.Models.AutomaticAccrualRequest_timeUnit>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("amount", Amount);
            writer.WriteEnumValue<global::ClockifyClient.Models.AutomaticAccrualRequest_period>("period", Period);
            writer.WriteEnumValue<global::ClockifyClient.Models.AutomaticAccrualRequest_timeUnit>("timeUnit", TimeUnit);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
