// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ClockifyClient.Models
{
    /// <summary>Represents a time entry automatic lock type enum.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AutomaticLockDtoV1_type
    {
        [EnumMember(Value = "WEEKLY")]
        #pragma warning disable CS1591
        WEEKLY,
        #pragma warning restore CS1591
        [EnumMember(Value = "MONTHLY")]
        #pragma warning disable CS1591
        MONTHLY,
        #pragma warning restore CS1591
        [EnumMember(Value = "OLDER_THAN")]
        #pragma warning disable CS1591
        OLDER_THAN,
        #pragma warning restore CS1591
    }
}
