// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ClockifyClient.Models
{
    /// <summary>Represents automatic accrual&apos;s period</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AutomaticAccrualDto_period
    {
        [EnumMember(Value = "MONTH")]
        #pragma warning disable CS1591
        MONTH,
        #pragma warning restore CS1591
        [EnumMember(Value = "YEAR")]
        #pragma warning disable CS1591
        YEAR,
        #pragma warning restore CS1591
    }
}
