// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ClockifyClient.Models
{
    /// <summary>Provide icon.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreatePolicyRequestV1_icon
    {
        [EnumMember(Value = "UMBRELLA")]
        #pragma warning disable CS1591
        UMBRELLA,
        #pragma warning restore CS1591
        [EnumMember(Value = "SNOWFLAKE")]
        #pragma warning disable CS1591
        SNOWFLAKE,
        #pragma warning restore CS1591
        [EnumMember(Value = "FAMILY")]
        #pragma warning disable CS1591
        FAMILY,
        #pragma warning restore CS1591
        [EnumMember(Value = "PLANE")]
        #pragma warning disable CS1591
        PLANE,
        #pragma warning restore CS1591
        [EnumMember(Value = "STETHOSCOPE")]
        #pragma warning disable CS1591
        STETHOSCOPE,
        #pragma warning restore CS1591
        [EnumMember(Value = "HEALTH_METRICS")]
        #pragma warning disable CS1591
        HEALTH_METRICS,
        #pragma warning restore CS1591
        [EnumMember(Value = "CHILDCARE")]
        #pragma warning disable CS1591
        CHILDCARE,
        #pragma warning restore CS1591
        [EnumMember(Value = "LUGGAGE")]
        #pragma warning disable CS1591
        LUGGAGE,
        #pragma warning restore CS1591
        [EnumMember(Value = "MONETIZATION")]
        #pragma warning disable CS1591
        MONETIZATION,
        #pragma warning restore CS1591
        [EnumMember(Value = "CALENDAR")]
        #pragma warning disable CS1591
        CALENDAR,
        #pragma warning restore CS1591
    }
}
