// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ClockifyClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateInvoiceItemRequestV1 : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Represents taxes applied to the invoice item. Applies only when the specified taxes are active on the invoice.</summary>
        public global::ClockifyClient.Models.CreateInvoiceItemRequestV1_applyTaxes? ApplyTaxes { get; set; }
        /// <summary>Represents an invoice item description.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Represents an item type.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ItemType { get; set; }
#nullable restore
#else
        public string ItemType { get; set; }
#endif
        /// <summary>Represents an item quantity.</summary>
        public long? Quantity { get; set; }
        /// <summary>Represents an item unit price.</summary>
        public long? UnitPrice { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::ClockifyClient.Models.CreateInvoiceItemRequestV1"/> and sets the default values.
        /// </summary>
        public CreateInvoiceItemRequestV1()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ClockifyClient.Models.CreateInvoiceItemRequestV1"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ClockifyClient.Models.CreateInvoiceItemRequestV1 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ClockifyClient.Models.CreateInvoiceItemRequestV1();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "applyTaxes", n => { ApplyTaxes = n.GetEnumValue<global::ClockifyClient.Models.CreateInvoiceItemRequestV1_applyTaxes>(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "itemType", n => { ItemType = n.GetStringValue(); } },
                { "quantity", n => { Quantity = n.GetLongValue(); } },
                { "unitPrice", n => { UnitPrice = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::ClockifyClient.Models.CreateInvoiceItemRequestV1_applyTaxes>("applyTaxes", ApplyTaxes);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("itemType", ItemType);
            writer.WriteLongValue("quantity", Quantity);
            writer.WriteLongValue("unitPrice", UnitPrice);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
