// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ClockifyClient.Models
{
    /// <summary>Represents custom field entity type</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CustomFieldRequestV1_entityType
    {
        [EnumMember(Value = "TIMEENTRY")]
        #pragma warning disable CS1591
        TIMEENTRY,
        #pragma warning restore CS1591
        [EnumMember(Value = "USER")]
        #pragma warning disable CS1591
        USER,
        #pragma warning restore CS1591
    }
}
