// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ClockifyClient.Models
{
    /// <summary>Represents custom field number condition.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CustomFieldFilterV1_numberCondition
    {
        [EnumMember(Value = "EQUAL")]
        #pragma warning disable CS1591
        EQUAL,
        #pragma warning restore CS1591
        [EnumMember(Value = "GREATER_THAN")]
        #pragma warning disable CS1591
        GREATER_THAN,
        #pragma warning restore CS1591
        [EnumMember(Value = "LESS_THAN")]
        #pragma warning disable CS1591
        LESS_THAN,
        #pragma warning restore CS1591
    }
}
