// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ClockifyClient.Models
{
    /// <summary>
    /// Represents custom field type.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CustomFieldType : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The CHECKBOX property</summary>
        public global::ClockifyClient.Models.CustomFieldType_CHECKBOX? CHECKBOX { get; set; }
        /// <summary>The DROPDOWN_MULTIPLE property</summary>
        public global::ClockifyClient.Models.CustomFieldType_DROPDOWN_MULTIPLE? DROPDOWNMULTIPLE { get; set; }
        /// <summary>The DROPDOWN_SINGLE property</summary>
        public global::ClockifyClient.Models.CustomFieldType_DROPDOWN_SINGLE? DROPDOWNSINGLE { get; set; }
        /// <summary>The LINK property</summary>
        public global::ClockifyClient.Models.CustomFieldType_LINK? LINK { get; set; }
        /// <summary>The NUMBER property</summary>
        public global::ClockifyClient.Models.CustomFieldType_NUMBER? NUMBER { get; set; }
        /// <summary>The TXT property</summary>
        public global::ClockifyClient.Models.CustomFieldType_TXT? TXT { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::ClockifyClient.Models.CustomFieldType"/> and sets the default values.
        /// </summary>
        public CustomFieldType()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ClockifyClient.Models.CustomFieldType"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ClockifyClient.Models.CustomFieldType CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ClockifyClient.Models.CustomFieldType();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "CHECKBOX", n => { CHECKBOX = n.GetEnumValue<global::ClockifyClient.Models.CustomFieldType_CHECKBOX>(); } },
                { "DROPDOWN_MULTIPLE", n => { DROPDOWNMULTIPLE = n.GetEnumValue<global::ClockifyClient.Models.CustomFieldType_DROPDOWN_MULTIPLE>(); } },
                { "DROPDOWN_SINGLE", n => { DROPDOWNSINGLE = n.GetEnumValue<global::ClockifyClient.Models.CustomFieldType_DROPDOWN_SINGLE>(); } },
                { "LINK", n => { LINK = n.GetEnumValue<global::ClockifyClient.Models.CustomFieldType_LINK>(); } },
                { "NUMBER", n => { NUMBER = n.GetEnumValue<global::ClockifyClient.Models.CustomFieldType_NUMBER>(); } },
                { "TXT", n => { TXT = n.GetEnumValue<global::ClockifyClient.Models.CustomFieldType_TXT>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::ClockifyClient.Models.CustomFieldType_CHECKBOX>("CHECKBOX", CHECKBOX);
            writer.WriteEnumValue<global::ClockifyClient.Models.CustomFieldType_DROPDOWN_MULTIPLE>("DROPDOWN_MULTIPLE", DROPDOWNMULTIPLE);
            writer.WriteEnumValue<global::ClockifyClient.Models.CustomFieldType_DROPDOWN_SINGLE>("DROPDOWN_SINGLE", DROPDOWNSINGLE);
            writer.WriteEnumValue<global::ClockifyClient.Models.CustomFieldType_LINK>("LINK", LINK);
            writer.WriteEnumValue<global::ClockifyClient.Models.CustomFieldType_NUMBER>("NUMBER", NUMBER);
            writer.WriteEnumValue<global::ClockifyClient.Models.CustomFieldType_TXT>("TXT", TXT);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
