// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ClockifyClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum EstimateResetDto_interval
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "WEEKLY")]
        #pragma warning disable CS1591
        WEEKLY,
        #pragma warning restore CS1591
        [EnumMember(Value = "MONTHLY")]
        #pragma warning disable CS1591
        MONTHLY,
        #pragma warning restore CS1591
        [EnumMember(Value = "YEARLY")]
        #pragma warning disable CS1591
        YEARLY,
        #pragma warning restore CS1591
    }
}
