// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ClockifyClient.Models
{
    /// <summary>Represents export fields.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ExpenseReportDtoV1_exportFields
    {
        [EnumMember(Value = "PROJECT")]
        #pragma warning disable CS1591
        PROJECT,
        #pragma warning restore CS1591
        [EnumMember(Value = "CLIENT")]
        #pragma warning disable CS1591
        CLIENT,
        #pragma warning restore CS1591
        [EnumMember(Value = "TASK")]
        #pragma warning disable CS1591
        TASK,
        #pragma warning restore CS1591
        [EnumMember(Value = "DESCRIPTION")]
        #pragma warning disable CS1591
        DESCRIPTION,
        #pragma warning restore CS1591
        [EnumMember(Value = "USER")]
        #pragma warning disable CS1591
        USER,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAGS")]
        #pragma warning disable CS1591
        TAGS,
        #pragma warning restore CS1591
        [EnumMember(Value = "START_DATE")]
        #pragma warning disable CS1591
        START_DATE,
        #pragma warning restore CS1591
        [EnumMember(Value = "START_TIME")]
        #pragma warning disable CS1591
        START_TIME,
        #pragma warning restore CS1591
        [EnumMember(Value = "END_TIME")]
        #pragma warning disable CS1591
        END_TIME,
        #pragma warning restore CS1591
        [EnumMember(Value = "DURATION")]
        #pragma warning disable CS1591
        DURATION,
        #pragma warning restore CS1591
        [EnumMember(Value = "BILLABLE_AMOUNT")]
        #pragma warning disable CS1591
        BILLABLE_AMOUNT,
        #pragma warning restore CS1591
        [EnumMember(Value = "COST_AMOUNT")]
        #pragma warning disable CS1591
        COST_AMOUNT,
        #pragma warning restore CS1591
        [EnumMember(Value = "PROFIT")]
        #pragma warning disable CS1591
        PROFIT,
        #pragma warning restore CS1591
        [EnumMember(Value = "EMAIL")]
        #pragma warning disable CS1591
        EMAIL,
        #pragma warning restore CS1591
        [EnumMember(Value = "BILLABLE")]
        #pragma warning disable CS1591
        BILLABLE,
        #pragma warning restore CS1591
        [EnumMember(Value = "BILLABLE_H")]
        #pragma warning disable CS1591
        BILLABLE_H,
        #pragma warning restore CS1591
        [EnumMember(Value = "NON_BILLABLE_H")]
        #pragma warning disable CS1591
        NON_BILLABLE_H,
        #pragma warning restore CS1591
        [EnumMember(Value = "END_DATE")]
        #pragma warning disable CS1591
        END_DATE,
        #pragma warning restore CS1591
        [EnumMember(Value = "DECIMAL_DURATION")]
        #pragma warning disable CS1591
        DECIMAL_DURATION,
        #pragma warning restore CS1591
        [EnumMember(Value = "BILLABLE_RATE")]
        #pragma warning disable CS1591
        BILLABLE_RATE,
        #pragma warning restore CS1591
        [EnumMember(Value = "COST_RATE")]
        #pragma warning disable CS1591
        COST_RATE,
        #pragma warning restore CS1591
        [EnumMember(Value = "APPROVAL")]
        #pragma warning disable CS1591
        APPROVAL,
        #pragma warning restore CS1591
        [EnumMember(Value = "BAR_CHART")]
        #pragma warning disable CS1591
        BAR_CHART,
        #pragma warning restore CS1591
        [EnumMember(Value = "PIE_CHART_1")]
        #pragma warning disable CS1591
        PIE_CHART_1,
        #pragma warning restore CS1591
        [EnumMember(Value = "PIE_CHART_2")]
        #pragma warning disable CS1591
        PIE_CHART_2,
        #pragma warning restore CS1591
        [EnumMember(Value = "PIE_CHART_3")]
        #pragma warning disable CS1591
        PIE_CHART_3,
        #pragma warning restore CS1591
        [EnumMember(Value = "RTL")]
        #pragma warning disable CS1591
        RTL,
        #pragma warning restore CS1591
        [EnumMember(Value = "TOTAL")]
        #pragma warning disable CS1591
        TOTAL,
        #pragma warning restore CS1591
        [EnumMember(Value = "SUBGROUP")]
        #pragma warning disable CS1591
        SUBGROUP,
        #pragma warning restore CS1591
        [EnumMember(Value = "GROUP")]
        #pragma warning disable CS1591
        GROUP,
        #pragma warning restore CS1591
        [EnumMember(Value = "DATE")]
        #pragma warning disable CS1591
        DATE,
        #pragma warning restore CS1591
        [EnumMember(Value = "TIME")]
        #pragma warning disable CS1591
        TIME,
        #pragma warning restore CS1591
        [EnumMember(Value = "CATEGORY")]
        #pragma warning disable CS1591
        CATEGORY,
        #pragma warning restore CS1591
        [EnumMember(Value = "NOTE")]
        #pragma warning disable CS1591
        NOTE,
        #pragma warning restore CS1591
        [EnumMember(Value = "AMOUNT")]
        #pragma warning disable CS1591
        AMOUNT,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVOICED")]
        #pragma warning disable CS1591
        INVOICED,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVOICE_ID")]
        #pragma warning disable CS1591
        INVOICE_ID,
        #pragma warning restore CS1591
        [EnumMember(Value = "CATEGORY_NO_OF_UNITS")]
        #pragma warning disable CS1591
        CATEGORY_NO_OF_UNITS,
        #pragma warning restore CS1591
        [EnumMember(Value = "CATEGORY_UNIT")]
        #pragma warning disable CS1591
        CATEGORY_UNIT,
        #pragma warning restore CS1591
        [EnumMember(Value = "KIOSK")]
        #pragma warning disable CS1591
        KIOSK,
        #pragma warning restore CS1591
        [EnumMember(Value = "TYPE")]
        #pragma warning disable CS1591
        TYPE,
        #pragma warning restore CS1591
        [EnumMember(Value = "BREAK")]
        #pragma warning disable CS1591
        BREAK,
        #pragma warning restore CS1591
        [EnumMember(Value = "NOTES")]
        #pragma warning disable CS1591
        NOTES,
        #pragma warning restore CS1591
        [EnumMember(Value = "BILLABLE_TOTAL")]
        #pragma warning disable CS1591
        BILLABLE_TOTAL,
        #pragma warning restore CS1591
        [EnumMember(Value = "RECEIPTS")]
        #pragma warning disable CS1591
        RECEIPTS,
        #pragma warning restore CS1591
        [EnumMember(Value = "EXPENSE_TOTAL")]
        #pragma warning disable CS1591
        EXPENSE_TOTAL,
        #pragma warning restore CS1591
        [EnumMember(Value = "DATE_OF_CREATION")]
        #pragma warning disable CS1591
        DATE_OF_CREATION,
        #pragma warning restore CS1591
        [EnumMember(Value = "DATE_OF_APPROVAL")]
        #pragma warning disable CS1591
        DATE_OF_APPROVAL,
        #pragma warning restore CS1591
        [EnumMember(Value = "NAME")]
        #pragma warning disable CS1591
        NAME,
        #pragma warning restore CS1591
        [EnumMember(Value = "ROLE")]
        #pragma warning disable CS1591
        ROLE,
        #pragma warning restore CS1591
        [EnumMember(Value = "PROJECTS")]
        #pragma warning disable CS1591
        PROJECTS,
        #pragma warning restore CS1591
        [EnumMember(Value = "STATUS")]
        #pragma warning disable CS1591
        STATUS,
        #pragma warning restore CS1591
        [EnumMember(Value = "WEEK_START")]
        #pragma warning disable CS1591
        WEEK_START,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKING_DAYS")]
        #pragma warning disable CS1591
        WORKING_DAYS,
        #pragma warning restore CS1591
        [EnumMember(Value = "TEAM_MEMBERS")]
        #pragma warning disable CS1591
        TEAM_MEMBERS,
        #pragma warning restore CS1591
        [EnumMember(Value = "DAILY_WORK_CAPACITY")]
        #pragma warning disable CS1591
        DAILY_WORK_CAPACITY,
        #pragma warning restore CS1591
        [EnumMember(Value = "VISIBILITY")]
        #pragma warning disable CS1591
        VISIBILITY,
        #pragma warning restore CS1591
        [EnumMember(Value = "BILLABILITY")]
        #pragma warning disable CS1591
        BILLABILITY,
        #pragma warning restore CS1591
        [EnumMember(Value = "TASKS")]
        #pragma warning disable CS1591
        TASKS,
        #pragma warning restore CS1591
        [EnumMember(Value = "TRACKED_H")]
        #pragma warning disable CS1591
        TRACKED_H,
        #pragma warning restore CS1591
        [EnumMember(Value = "ESTIMATED_H")]
        #pragma warning disable CS1591
        ESTIMATED_H,
        #pragma warning restore CS1591
        [EnumMember(Value = "REMAINING_H")]
        #pragma warning disable CS1591
        REMAINING_H,
        #pragma warning restore CS1591
        [EnumMember(Value = "OVERAGE_H")]
        #pragma warning disable CS1591
        OVERAGE_H,
        #pragma warning restore CS1591
        [EnumMember(Value = "TRACKED_BUDGET")]
        #pragma warning disable CS1591
        TRACKED_BUDGET,
        #pragma warning restore CS1591
        [EnumMember(Value = "ESTIMATED_BUDGET")]
        #pragma warning disable CS1591
        ESTIMATED_BUDGET,
        #pragma warning restore CS1591
        [EnumMember(Value = "REMAINING_BUDGET")]
        #pragma warning disable CS1591
        REMAINING_BUDGET,
        #pragma warning restore CS1591
        [EnumMember(Value = "OVERAGE_BUDGET")]
        #pragma warning disable CS1591
        OVERAGE_BUDGET,
        #pragma warning restore CS1591
        [EnumMember(Value = "PROGRESS")]
        #pragma warning disable CS1591
        PROGRESS,
        #pragma warning restore CS1591
        [EnumMember(Value = "RECURRING_ESTIMATE")]
        #pragma warning disable CS1591
        RECURRING_ESTIMATE,
        #pragma warning restore CS1591
        [EnumMember(Value = "EXPENSES")]
        #pragma warning disable CS1591
        EXPENSES,
        #pragma warning restore CS1591
        [EnumMember(Value = "BILLABLE_EXPENSES")]
        #pragma warning disable CS1591
        BILLABLE_EXPENSES,
        #pragma warning restore CS1591
        [EnumMember(Value = "NON_BILLABLE_EXPENSES")]
        #pragma warning disable CS1591
        NON_BILLABLE_EXPENSES,
        #pragma warning restore CS1591
        [EnumMember(Value = "ADDITIONAL_FIELDS")]
        #pragma warning disable CS1591
        ADDITIONAL_FIELDS,
        #pragma warning restore CS1591
        [EnumMember(Value = "PROJECT_MEMBERS")]
        #pragma warning disable CS1591
        PROJECT_MEMBERS,
        #pragma warning restore CS1591
        [EnumMember(Value = "PROJECT_MANAGER")]
        #pragma warning disable CS1591
        PROJECT_MANAGER,
        #pragma warning restore CS1591
        [EnumMember(Value = "APPROVED_BY")]
        #pragma warning disable CS1591
        APPROVED_BY,
        #pragma warning restore CS1591
        [EnumMember(Value = "ISSUE_DATE")]
        #pragma warning disable CS1591
        ISSUE_DATE,
        #pragma warning restore CS1591
        [EnumMember(Value = "DUE_ON")]
        #pragma warning disable CS1591
        DUE_ON,
        #pragma warning restore CS1591
        [EnumMember(Value = "BALANCE")]
        #pragma warning disable CS1591
        BALANCE,
        #pragma warning restore CS1591
    }
}
