// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ClockifyClient.Models
{
    /// <summary>Represents sort order</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ExpenseReportFilterV1_sortOrder
    {
        [EnumMember(Value = "ASCENDING")]
        #pragma warning disable CS1591
        ASCENDING,
        #pragma warning restore CS1591
        [EnumMember(Value = "DESCENDING")]
        #pragma warning disable CS1591
        DESCENDING,
        #pragma warning restore CS1591
    }
}
