// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ClockifyClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum FeatureSubscriptionType_STANDARD_2021
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "PREMIUM")]
        #pragma warning disable CS1591
        PREMIUM,
        #pragma warning restore CS1591
        [EnumMember(Value = "PREMIUM_YEAR")]
        #pragma warning disable CS1591
        PREMIUM_YEAR,
        #pragma warning restore CS1591
        [EnumMember(Value = "SPECIAL")]
        #pragma warning disable CS1591
        SPECIAL,
        #pragma warning restore CS1591
        [EnumMember(Value = "SPECIAL_YEAR")]
        #pragma warning disable CS1591
        SPECIAL_YEAR,
        #pragma warning restore CS1591
        [EnumMember(Value = "TRIAL")]
        #pragma warning disable CS1591
        TRIAL,
        #pragma warning restore CS1591
        [EnumMember(Value = "ENTERPRISE")]
        #pragma warning disable CS1591
        ENTERPRISE,
        #pragma warning restore CS1591
        [EnumMember(Value = "ENTERPRISE_YEAR")]
        #pragma warning disable CS1591
        ENTERPRISE_YEAR,
        #pragma warning restore CS1591
        [EnumMember(Value = "BASIC_2021")]
        #pragma warning disable CS1591
        BASIC_2021,
        #pragma warning restore CS1591
        [EnumMember(Value = "BASIC_YEAR_2021")]
        #pragma warning disable CS1591
        BASIC_YEAR_2021,
        #pragma warning restore CS1591
        [EnumMember(Value = "STANDARD_2021")]
        #pragma warning disable CS1591
        STANDARD_2021,
        #pragma warning restore CS1591
        [EnumMember(Value = "STANDARD_YEAR_2021")]
        #pragma warning disable CS1591
        STANDARD_YEAR_2021,
        #pragma warning restore CS1591
        [EnumMember(Value = "PRO_2021")]
        #pragma warning disable CS1591
        PRO_2021,
        #pragma warning restore CS1591
        [EnumMember(Value = "PRO_YEAR_2021")]
        #pragma warning disable CS1591
        PRO_YEAR_2021,
        #pragma warning restore CS1591
        [EnumMember(Value = "ENTERPRISE_2021")]
        #pragma warning disable CS1591
        ENTERPRISE_2021,
        #pragma warning restore CS1591
        [EnumMember(Value = "ENTERPRISE_YEAR_2021")]
        #pragma warning disable CS1591
        ENTERPRISE_YEAR_2021,
        #pragma warning restore CS1591
        [EnumMember(Value = "BUNDLE_2024")]
        #pragma warning disable CS1591
        BUNDLE_2024,
        #pragma warning restore CS1591
        [EnumMember(Value = "BUNDLE_YEAR_2024")]
        #pragma warning disable CS1591
        BUNDLE_YEAR_2024,
        #pragma warning restore CS1591
        [EnumMember(Value = "SELF_HOSTED")]
        #pragma warning disable CS1591
        SELF_HOSTED,
        #pragma warning restore CS1591
        [EnumMember(Value = "FREE")]
        #pragma warning disable CS1591
        FREE,
        #pragma warning restore CS1591
    }
}
