// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ClockifyClient.Models
{
    /// <summary>Filters assignments by status.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GetUserTotalsRequestV1_statusFilter
    {
        [EnumMember(Value = "PUBLISHED")]
        #pragma warning disable CS1591
        PUBLISHED,
        #pragma warning restore CS1591
        [EnumMember(Value = "UNPUBLISHED")]
        #pragma warning disable CS1591
        UNPUBLISHED,
        #pragma warning restore CS1591
        [EnumMember(Value = "ALL")]
        #pragma warning disable CS1591
        ALL,
        #pragma warning restore CS1591
    }
}
