// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ClockifyClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetUserTotalsRequestV1 : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Represents end date in yyyy-MM-ddThh:mm:ssZ format.</summary>
        public DateTimeOffset? End { get; set; }
        /// <summary>Page number.</summary>
        public int? Page { get; set; }
        /// <summary>Page size.</summary>
        public int? PageSize { get; set; }
        /// <summary>Represents keyword for searching users by name or email.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Search { get; set; }
#nullable restore
#else
        public string Search { get; set; }
#endif
        /// <summary>Represents start date in yyyy-MM-ddThh:mm:ssZ format.</summary>
        public DateTimeOffset? Start { get; set; }
        /// <summary>Filters assignments by status.</summary>
        public global::ClockifyClient.Models.GetUserTotalsRequestV1_statusFilter? StatusFilter { get; set; }
        /// <summary>Represents a user filter request object.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ClockifyClient.Models.ContainsUsersFilterRequestV1? UserFilter { get; set; }
#nullable restore
#else
        public global::ClockifyClient.Models.ContainsUsersFilterRequestV1 UserFilter { get; set; }
#endif
        /// <summary>Represents a user group filter request object.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ClockifyClient.Models.ContainsUserGroupFilterRequestV1? UserGroupFilter { get; set; }
#nullable restore
#else
        public global::ClockifyClient.Models.ContainsUserGroupFilterRequestV1 UserGroupFilter { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::ClockifyClient.Models.GetUserTotalsRequestV1"/> and sets the default values.
        /// </summary>
        public GetUserTotalsRequestV1()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ClockifyClient.Models.GetUserTotalsRequestV1"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ClockifyClient.Models.GetUserTotalsRequestV1 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ClockifyClient.Models.GetUserTotalsRequestV1();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "end", n => { End = n.GetDateTimeOffsetValue(); } },
                { "page", n => { Page = n.GetIntValue(); } },
                { "pageSize", n => { PageSize = n.GetIntValue(); } },
                { "search", n => { Search = n.GetStringValue(); } },
                { "start", n => { Start = n.GetDateTimeOffsetValue(); } },
                { "statusFilter", n => { StatusFilter = n.GetEnumValue<global::ClockifyClient.Models.GetUserTotalsRequestV1_statusFilter>(); } },
                { "userFilter", n => { UserFilter = n.GetObjectValue<global::ClockifyClient.Models.ContainsUsersFilterRequestV1>(global::ClockifyClient.Models.ContainsUsersFilterRequestV1.CreateFromDiscriminatorValue); } },
                { "userGroupFilter", n => { UserGroupFilter = n.GetObjectValue<global::ClockifyClient.Models.ContainsUserGroupFilterRequestV1>(global::ClockifyClient.Models.ContainsUserGroupFilterRequestV1.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("end", End);
            writer.WriteIntValue("page", Page);
            writer.WriteIntValue("pageSize", PageSize);
            writer.WriteStringValue("search", Search);
            writer.WriteDateTimeOffsetValue("start", Start);
            writer.WriteEnumValue<global::ClockifyClient.Models.GetUserTotalsRequestV1_statusFilter>("statusFilter", StatusFilter);
            writer.WriteObjectValue<global::ClockifyClient.Models.ContainsUsersFilterRequestV1>("userFilter", UserFilter);
            writer.WriteObjectValue<global::ClockifyClient.Models.ContainsUserGroupFilterRequestV1>("userGroupFilter", UserGroupFilter);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
