// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ClockifyClient.Models
{
    /// <summary>Represents a time entry group type.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ImportTimeEntriesAndExpensesRequestV1_timeEntryGroupType
    {
        [EnumMember(Value = "SINGLE_ITEM")]
        #pragma warning disable CS1591
        SINGLE_ITEM,
        #pragma warning restore CS1591
        [EnumMember(Value = "GROUPED")]
        #pragma warning disable CS1591
        GROUPED,
        #pragma warning restore CS1591
        [EnumMember(Value = "DETAILED")]
        #pragma warning disable CS1591
        DETAILED,
        #pragma warning restore CS1591
    }
}
