// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ClockifyClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ImportTimeEntriesAndExpensesRequestV1 : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Represents a set of expense fields to include when using the DETAILED expense grouping type.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::ClockifyClient.Models.ImportTimeEntriesAndExpensesRequestV1_expenseFieldsForDetailedGroup?>? ExpenseFieldsForDetailedGroup { get; set; }
#nullable restore
#else
        public List<global::ClockifyClient.Models.ImportTimeEntriesAndExpensesRequestV1_expenseFieldsForDetailedGroup?> ExpenseFieldsForDetailedGroup { get; set; }
#endif
        /// <summary>Represents a group field when using the GROUPED expense group type.</summary>
        public global::ClockifyClient.Models.ImportTimeEntriesAndExpensesRequestV1_expensesGroupBy? ExpensesGroupBy { get; set; }
        /// <summary>Represents an expense group type.</summary>
        public global::ClockifyClient.Models.ImportTimeEntriesAndExpensesRequestV1_expensesGroupType? ExpensesGroupType { get; set; }
        /// <summary>Represents date and time in the yyyy-MM-ddThh:mm:ssZ format.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? From { get; set; }
#nullable restore
#else
        public string From { get; set; }
#endif
        /// <summary>Indicates if billable expenses should be imported alongside time entries.</summary>
        public bool? ImportExpenses { get; set; }
        /// <summary>Represents a project filter for imported items.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ClockifyClient.Models.ContainsArchivedFilterRequest? ProjectFilter { get; set; }
#nullable restore
#else
        public global::ClockifyClient.Models.ContainsArchivedFilterRequest ProjectFilter { get; set; }
#endif
        /// <summary>Indicates if imported time entry durations should be rounded to the nearest 15 minute interval.</summary>
        public bool? RoundTimeEntryDuration { get; set; }
        /// <summary>Represents a set of time entry fields to include when using DETAILED time entry grouping type.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::ClockifyClient.Models.ImportTimeEntriesAndExpensesRequestV1_timeEntryFieldsForDetailedGroup?>? TimeEntryFieldsForDetailedGroup { get; set; }
#nullable restore
#else
        public List<global::ClockifyClient.Models.ImportTimeEntriesAndExpensesRequestV1_timeEntryFieldsForDetailedGroup?> TimeEntryFieldsForDetailedGroup { get; set; }
#endif
        /// <summary>Represents a time entry group type.</summary>
        public global::ClockifyClient.Models.ImportTimeEntriesAndExpensesRequestV1_timeEntryGroupType? TimeEntryGroupType { get; set; }
        /// <summary>Represents a primary group field when using the GROUPED time entry grouping type.</summary>
        public global::ClockifyClient.Models.ImportTimeEntriesAndExpensesRequestV1_timeEntryPrimaryGroupBy? TimeEntryPrimaryGroupBy { get; set; }
        /// <summary>Represents a secondary group field when using the GROUPED time entry grouping type. Should not have the same grouping type as the primary group field.</summary>
        public global::ClockifyClient.Models.ImportTimeEntriesAndExpensesRequestV1_timeEntrySecondaryGroupBy? TimeEntrySecondaryGroupBy { get; set; }
        /// <summary>Represents date and time in the yyyy-MM-ddThh:mm:ssZ format.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? To { get; set; }
#nullable restore
#else
        public string To { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::ClockifyClient.Models.ImportTimeEntriesAndExpensesRequestV1"/> and sets the default values.
        /// </summary>
        public ImportTimeEntriesAndExpensesRequestV1()
        {
            AdditionalData = new Dictionary<string, object>();
            ExpensesGroupBy = global::ClockifyClient.Models.ImportTimeEntriesAndExpensesRequestV1_expensesGroupBy.PROJECT;
            ExpensesGroupType = global::ClockifyClient.Models.ImportTimeEntriesAndExpensesRequestV1_expensesGroupType.DETAILED;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ClockifyClient.Models.ImportTimeEntriesAndExpensesRequestV1"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ClockifyClient.Models.ImportTimeEntriesAndExpensesRequestV1 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ClockifyClient.Models.ImportTimeEntriesAndExpensesRequestV1();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "expenseFieldsForDetailedGroup", n => { ExpenseFieldsForDetailedGroup = n.GetCollectionOfEnumValues<global::ClockifyClient.Models.ImportTimeEntriesAndExpensesRequestV1_expenseFieldsForDetailedGroup>()?.AsList(); } },
                { "expensesGroupBy", n => { ExpensesGroupBy = n.GetEnumValue<global::ClockifyClient.Models.ImportTimeEntriesAndExpensesRequestV1_expensesGroupBy>(); } },
                { "expensesGroupType", n => { ExpensesGroupType = n.GetEnumValue<global::ClockifyClient.Models.ImportTimeEntriesAndExpensesRequestV1_expensesGroupType>(); } },
                { "from", n => { From = n.GetStringValue(); } },
                { "importExpenses", n => { ImportExpenses = n.GetBoolValue(); } },
                { "projectFilter", n => { ProjectFilter = n.GetObjectValue<global::ClockifyClient.Models.ContainsArchivedFilterRequest>(global::ClockifyClient.Models.ContainsArchivedFilterRequest.CreateFromDiscriminatorValue); } },
                { "roundTimeEntryDuration", n => { RoundTimeEntryDuration = n.GetBoolValue(); } },
                { "timeEntryFieldsForDetailedGroup", n => { TimeEntryFieldsForDetailedGroup = n.GetCollectionOfEnumValues<global::ClockifyClient.Models.ImportTimeEntriesAndExpensesRequestV1_timeEntryFieldsForDetailedGroup>()?.AsList(); } },
                { "timeEntryGroupType", n => { TimeEntryGroupType = n.GetEnumValue<global::ClockifyClient.Models.ImportTimeEntriesAndExpensesRequestV1_timeEntryGroupType>(); } },
                { "timeEntryPrimaryGroupBy", n => { TimeEntryPrimaryGroupBy = n.GetEnumValue<global::ClockifyClient.Models.ImportTimeEntriesAndExpensesRequestV1_timeEntryPrimaryGroupBy>(); } },
                { "timeEntrySecondaryGroupBy", n => { TimeEntrySecondaryGroupBy = n.GetEnumValue<global::ClockifyClient.Models.ImportTimeEntriesAndExpensesRequestV1_timeEntrySecondaryGroupBy>(); } },
                { "to", n => { To = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfEnumValues<global::ClockifyClient.Models.ImportTimeEntriesAndExpensesRequestV1_expenseFieldsForDetailedGroup>("expenseFieldsForDetailedGroup", ExpenseFieldsForDetailedGroup);
            writer.WriteEnumValue<global::ClockifyClient.Models.ImportTimeEntriesAndExpensesRequestV1_expensesGroupBy>("expensesGroupBy", ExpensesGroupBy);
            writer.WriteEnumValue<global::ClockifyClient.Models.ImportTimeEntriesAndExpensesRequestV1_expensesGroupType>("expensesGroupType", ExpensesGroupType);
            writer.WriteStringValue("from", From);
            writer.WriteBoolValue("importExpenses", ImportExpenses);
            writer.WriteObjectValue<global::ClockifyClient.Models.ContainsArchivedFilterRequest>("projectFilter", ProjectFilter);
            writer.WriteBoolValue("roundTimeEntryDuration", RoundTimeEntryDuration);
            writer.WriteCollectionOfEnumValues<global::ClockifyClient.Models.ImportTimeEntriesAndExpensesRequestV1_timeEntryFieldsForDetailedGroup>("timeEntryFieldsForDetailedGroup", TimeEntryFieldsForDetailedGroup);
            writer.WriteEnumValue<global::ClockifyClient.Models.ImportTimeEntriesAndExpensesRequestV1_timeEntryGroupType>("timeEntryGroupType", TimeEntryGroupType);
            writer.WriteEnumValue<global::ClockifyClient.Models.ImportTimeEntriesAndExpensesRequestV1_timeEntryPrimaryGroupBy>("timeEntryPrimaryGroupBy", TimeEntryPrimaryGroupBy);
            writer.WriteEnumValue<global::ClockifyClient.Models.ImportTimeEntriesAndExpensesRequestV1_timeEntrySecondaryGroupBy>("timeEntrySecondaryGroupBy", TimeEntrySecondaryGroupBy);
            writer.WriteStringValue("to", To);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
