// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ClockifyClient.Models
{
    /// <summary>Represents a set of expense fields to include when using the DETAILED expense grouping type.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ImportTimeEntriesAndExpensesRequestV1_expenseFieldsForDetailedGroup
    {
        [EnumMember(Value = "PROJECT")]
        #pragma warning disable CS1591
        PROJECT,
        #pragma warning restore CS1591
        [EnumMember(Value = "TASK")]
        #pragma warning disable CS1591
        TASK,
        #pragma warning restore CS1591
        [EnumMember(Value = "CATEGORY")]
        #pragma warning disable CS1591
        CATEGORY,
        #pragma warning restore CS1591
        [EnumMember(Value = "NOTE")]
        #pragma warning disable CS1591
        NOTE,
        #pragma warning restore CS1591
        [EnumMember(Value = "DATE")]
        #pragma warning disable CS1591
        DATE,
        #pragma warning restore CS1591
        [EnumMember(Value = "USER")]
        #pragma warning disable CS1591
        USER,
        #pragma warning restore CS1591
    }
}
