// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ClockifyClient.Models
{
    /// <summary>Represents the invoice item import type.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum InvoiceItemDto_importType
    {
        [EnumMember(Value = "NOT_IMPORTED")]
        #pragma warning disable CS1591
        NOT_IMPORTED,
        #pragma warning restore CS1591
        [EnumMember(Value = "TIME_ENTRY_IMPORT")]
        #pragma warning disable CS1591
        TIME_ENTRY_IMPORT,
        #pragma warning restore CS1591
        [EnumMember(Value = "EXPENSE_IMPORT")]
        #pragma warning disable CS1591
        EXPENSE_IMPORT,
        #pragma warning restore CS1591
    }
}
