// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ClockifyClient.Models
{
    /// <summary>Represents membership type enum.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum MembershipRequest_membershipType
    {
        [EnumMember(Value = "WORKSPACE")]
        #pragma warning disable CS1591
        WORKSPACE,
        #pragma warning restore CS1591
        [EnumMember(Value = "PROJECT")]
        #pragma warning disable CS1591
        PROJECT,
        #pragma warning restore CS1591
        [EnumMember(Value = "USERGROUP")]
        #pragma warning disable CS1591
        USERGROUP,
        #pragma warning restore CS1591
    }
}
