// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ClockifyClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum NegativeBalance_period
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "MONTH")]
        #pragma warning disable CS1591
        MONTH,
        #pragma warning restore CS1591
        [EnumMember(Value = "YEAR")]
        #pragma warning disable CS1591
        YEAR,
        #pragma warning restore CS1591
    }
}
