// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ClockifyClient.Models
{
    /// <summary>Represents time off request status type.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PtoTimeOffRequestStatus_statusType
    {
        [EnumMember(Value = "PENDING")]
        #pragma warning disable CS1591
        PENDING,
        #pragma warning restore CS1591
        [EnumMember(Value = "APPROVED")]
        #pragma warning disable CS1591
        APPROVED,
        #pragma warning restore CS1591
        [EnumMember(Value = "REJECTED")]
        #pragma warning disable CS1591
        REJECTED,
        #pragma warning restore CS1591
        [EnumMember(Value = "ALL")]
        #pragma warning disable CS1591
        ALL,
        #pragma warning restore CS1591
    }
}
