// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ClockifyClient.Models
{
    /// <summary>Represents view type.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PublishAssignmentsRequestV1_viewType
    {
        [EnumMember(Value = "PROJECTS")]
        #pragma warning disable CS1591
        PROJECTS,
        #pragma warning restore CS1591
        [EnumMember(Value = "TEAM")]
        #pragma warning disable CS1591
        TEAM,
        #pragma warning restore CS1591
        [EnumMember(Value = "ALL")]
        #pragma warning disable CS1591
        ALL,
        #pragma warning restore CS1591
    }
}
