// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ClockifyClient.Models
{
    /// <summary>Represents the scheduling exclude day enum.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SchedulingExcludeDay_type
    {
        [EnumMember(Value = "WEEKEND")]
        #pragma warning disable CS1591
        WEEKEND,
        #pragma warning restore CS1591
        [EnumMember(Value = "HOLIDAY")]
        #pragma warning disable CS1591
        HOLIDAY,
        #pragma warning restore CS1591
        [EnumMember(Value = "TIME_OFF")]
        #pragma warning disable CS1591
        TIME_OFF,
        #pragma warning restore CS1591
    }
}
