// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ClockifyClient.Models
{
    /// <summary>
    /// Represents summary report filter.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SummaryFilterV1 : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Represents group ids</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Groups { get; set; }
#nullable restore
#else
        public List<string> Groups { get; set; }
#endif
        /// <summary>If provided, you&apos;ll get sorted result by provided sort column.</summary>
        public global::ClockifyClient.Models.SummaryFilterV1_sortColumn? SortColumn { get; set; }
        /// <summary>If provided, you&apos;ll get sorted result by provided summary chart type.</summary>
        public global::ClockifyClient.Models.SummaryFilterV1_summaryChartType? SummaryChartType { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::ClockifyClient.Models.SummaryFilterV1"/> and sets the default values.
        /// </summary>
        public SummaryFilterV1()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ClockifyClient.Models.SummaryFilterV1"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ClockifyClient.Models.SummaryFilterV1 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::ClockifyClient.Models.SummaryFilterV1();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "groups", n => { Groups = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "sortColumn", n => { SortColumn = n.GetEnumValue<global::ClockifyClient.Models.SummaryFilterV1_sortColumn>(); } },
                { "summaryChartType", n => { SummaryChartType = n.GetEnumValue<global::ClockifyClient.Models.SummaryFilterV1_summaryChartType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("groups", Groups);
            writer.WriteEnumValue<global::ClockifyClient.Models.SummaryFilterV1_sortColumn>("sortColumn", SortColumn);
            writer.WriteEnumValue<global::ClockifyClient.Models.SummaryFilterV1_summaryChartType>("summaryChartType", SummaryChartType);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
