// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ClockifyClient.Models
{
    /// <summary>Provide date range type</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SummaryReportFilterV1_dateRangeType
    {
        [EnumMember(Value = "ABSOLUTE")]
        #pragma warning disable CS1591
        ABSOLUTE,
        #pragma warning restore CS1591
        [EnumMember(Value = "TODAY")]
        #pragma warning disable CS1591
        TODAY,
        #pragma warning restore CS1591
        [EnumMember(Value = "YESTERDAY")]
        #pragma warning disable CS1591
        YESTERDAY,
        #pragma warning restore CS1591
        [EnumMember(Value = "THIS_WEEK")]
        #pragma warning disable CS1591
        THIS_WEEK,
        #pragma warning restore CS1591
        [EnumMember(Value = "LAST_WEEK")]
        #pragma warning disable CS1591
        LAST_WEEK,
        #pragma warning restore CS1591
        [EnumMember(Value = "PAST_TWO_WEEKS")]
        #pragma warning disable CS1591
        PAST_TWO_WEEKS,
        #pragma warning restore CS1591
        [EnumMember(Value = "THIS_MONTH")]
        #pragma warning disable CS1591
        THIS_MONTH,
        #pragma warning restore CS1591
        [EnumMember(Value = "LAST_MONTH")]
        #pragma warning disable CS1591
        LAST_MONTH,
        #pragma warning restore CS1591
        [EnumMember(Value = "THIS_YEAR")]
        #pragma warning disable CS1591
        THIS_YEAR,
        #pragma warning restore CS1591
        [EnumMember(Value = "LAST_YEAR")]
        #pragma warning disable CS1591
        LAST_YEAR,
        #pragma warning restore CS1591
    }
}
