// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ClockifyClient.Models
{
    /// <summary>Represents an estimate type enum.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TimeEstimateDto_type
    {
        [EnumMember(Value = "AUTO")]
        #pragma warning disable CS1591
        AUTO,
        #pragma warning restore CS1591
        [EnumMember(Value = "MANUAL")]
        #pragma warning disable CS1591
        MANUAL,
        #pragma warning restore CS1591
    }
}
