// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ClockifyClient.Models
{
    /// <summary>Represents the half day period.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TimeOffRequestPeriodV1Request_halfDayPeriod
    {
        [EnumMember(Value = "FIRST_HALF")]
        #pragma warning disable CS1591
        FIRST_HALF,
        #pragma warning restore CS1591
        [EnumMember(Value = "SECOND_HALF")]
        #pragma warning disable CS1591
        SECOND_HALF,
        #pragma warning restore CS1591
        [EnumMember(Value = "NOT_DEFINED")]
        #pragma warning disable CS1591
        NOT_DEFINED,
        #pragma warning restore CS1591
    }
}
