// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ClockifyClient.Models
{
    /// <summary>
    /// Represents a list of value objects for user’s custom fields.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UpdateCustomFieldRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Represents custom field identifier across the system.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomFieldId { get; set; }
#nullable restore
#else
        public string CustomFieldId { get; set; }
#endif
        /// <summary>Represents a custom field value source type.</summary>
        public global::ClockifyClient.Models.UpdateCustomFieldRequest_sourceType? SourceType { get; set; }
        /// <summary>Represents a custom field&apos;s value.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ClockifyClient.Models.UpdateCustomFieldRequest_value? Value { get; set; }
#nullable restore
#else
        public global::ClockifyClient.Models.UpdateCustomFieldRequest_value Value { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::ClockifyClient.Models.UpdateCustomFieldRequest"/> and sets the default values.
        /// </summary>
        public UpdateCustomFieldRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ClockifyClient.Models.UpdateCustomFieldRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ClockifyClient.Models.UpdateCustomFieldRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ClockifyClient.Models.UpdateCustomFieldRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "customFieldId", n => { CustomFieldId = n.GetStringValue(); } },
                { "sourceType", n => { SourceType = n.GetEnumValue<global::ClockifyClient.Models.UpdateCustomFieldRequest_sourceType>(); } },
                { "value", n => { Value = n.GetObjectValue<global::ClockifyClient.Models.UpdateCustomFieldRequest_value>(global::ClockifyClient.Models.UpdateCustomFieldRequest_value.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("customFieldId", CustomFieldId);
            writer.WriteEnumValue<global::ClockifyClient.Models.UpdateCustomFieldRequest_sourceType>("sourceType", SourceType);
            writer.WriteObjectValue<global::ClockifyClient.Models.UpdateCustomFieldRequest_value>("value", Value);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
