// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ClockifyClient.Models
{
    /// <summary>Specifies the approval state to set.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UpdateApprovalRequest_state
    {
        [EnumMember(Value = "PENDING")]
        #pragma warning disable CS1591
        PENDING,
        #pragma warning restore CS1591
        [EnumMember(Value = "APPROVED")]
        #pragma warning disable CS1591
        APPROVED,
        #pragma warning restore CS1591
        [EnumMember(Value = "WITHDRAWN_SUBMISSION")]
        #pragma warning disable CS1591
        WITHDRAWN_SUBMISSION,
        #pragma warning restore CS1591
        [EnumMember(Value = "WITHDRAWN_APPROVAL")]
        #pragma warning disable CS1591
        WITHDRAWN_APPROVAL,
        #pragma warning restore CS1591
        [EnumMember(Value = "REJECTED")]
        #pragma warning disable CS1591
        REJECTED,
        #pragma warning restore CS1591
    }
}
