// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ClockifyClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UpdateInvoiceSettingsRequestV1 : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Represents an invoice default settings object.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ClockifyClient.Models.InvoiceDefaultSettingsRequestV1? Defaults { get; set; }
#nullable restore
#else
        public global::ClockifyClient.Models.InvoiceDefaultSettingsRequestV1 Defaults { get; set; }
#endif
        /// <summary>Represents an invoice export fields object.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ClockifyClient.Models.InvoiceExportFieldsRequest? ExportFields { get; set; }
#nullable restore
#else
        public global::ClockifyClient.Models.InvoiceExportFieldsRequest ExportFields { get; set; }
#endif
        /// <summary>Represents a label customization object.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ClockifyClient.Models.LabelsCustomizationRequest? Labels { get; set; }
#nullable restore
#else
        public global::ClockifyClient.Models.LabelsCustomizationRequest Labels { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::ClockifyClient.Models.UpdateInvoiceSettingsRequestV1"/> and sets the default values.
        /// </summary>
        public UpdateInvoiceSettingsRequestV1()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ClockifyClient.Models.UpdateInvoiceSettingsRequestV1"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ClockifyClient.Models.UpdateInvoiceSettingsRequestV1 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::ClockifyClient.Models.UpdateInvoiceSettingsRequestV1();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "defaults", n => { Defaults = n.GetObjectValue<global::ClockifyClient.Models.InvoiceDefaultSettingsRequestV1>(global::ClockifyClient.Models.InvoiceDefaultSettingsRequestV1.CreateFromDiscriminatorValue); } },
                { "exportFields", n => { ExportFields = n.GetObjectValue<global::ClockifyClient.Models.InvoiceExportFieldsRequest>(global::ClockifyClient.Models.InvoiceExportFieldsRequest.CreateFromDiscriminatorValue); } },
                { "labels", n => { Labels = n.GetObjectValue<global::ClockifyClient.Models.LabelsCustomizationRequest>(global::ClockifyClient.Models.LabelsCustomizationRequest.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::ClockifyClient.Models.InvoiceDefaultSettingsRequestV1>("defaults", Defaults);
            writer.WriteObjectValue<global::ClockifyClient.Models.InvoiceExportFieldsRequest>("exportFields", ExportFields);
            writer.WriteObjectValue<global::ClockifyClient.Models.LabelsCustomizationRequest>("labels", Labels);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
