// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ClockifyClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UserDtoV1 : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Represents user&apos;s active workspace identifier across the system.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ActiveWorkspace { get; set; }
#nullable restore
#else
        public string ActiveWorkspace { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Represents a list of value objects for user’s custom fields.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::ClockifyClient.Models.UserCustomFieldValueDtoV1>? CustomFields { get; set; }
#nullable restore
#else
        public List<global::ClockifyClient.Models.UserCustomFieldValueDtoV1> CustomFields { get; set; }
#endif
        /// <summary>Represents user default workspace identifier across the system.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefaultWorkspace { get; set; }
#nullable restore
#else
        public string DefaultWorkspace { get; set; }
#endif
        /// <summary>Represents email address of the user.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>Represents user identifier across the system.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Represents a list of membership objects.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::ClockifyClient.Models.MembershipDtoV1>? Memberships { get; set; }
#nullable restore
#else
        public List<global::ClockifyClient.Models.MembershipDtoV1> Memberships { get; set; }
#endif
        /// <summary>Represents name of the user.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Represents profile image path of the user.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProfilePicture { get; set; }
#nullable restore
#else
        public string ProfilePicture { get; set; }
#endif
        /// <summary>Represents user settings object.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ClockifyClient.Models.UserSettingsDtoV1? Settings { get; set; }
#nullable restore
#else
        public global::ClockifyClient.Models.UserSettingsDtoV1 Settings { get; set; }
#endif
        /// <summary>Represents account status enum.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ClockifyClient.Models.AccountStatus? Status { get; set; }
#nullable restore
#else
        public global::ClockifyClient.Models.AccountStatus Status { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::ClockifyClient.Models.UserDtoV1"/> and sets the default values.
        /// </summary>
        public UserDtoV1()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ClockifyClient.Models.UserDtoV1"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ClockifyClient.Models.UserDtoV1 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::ClockifyClient.Models.UserDtoV1();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "activeWorkspace", n => { ActiveWorkspace = n.GetStringValue(); } },
                { "customFields", n => { CustomFields = n.GetCollectionOfObjectValues<global::ClockifyClient.Models.UserCustomFieldValueDtoV1>(global::ClockifyClient.Models.UserCustomFieldValueDtoV1.CreateFromDiscriminatorValue)?.AsList(); } },
                { "defaultWorkspace", n => { DefaultWorkspace = n.GetStringValue(); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "memberships", n => { Memberships = n.GetCollectionOfObjectValues<global::ClockifyClient.Models.MembershipDtoV1>(global::ClockifyClient.Models.MembershipDtoV1.CreateFromDiscriminatorValue)?.AsList(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "profilePicture", n => { ProfilePicture = n.GetStringValue(); } },
                { "settings", n => { Settings = n.GetObjectValue<global::ClockifyClient.Models.UserSettingsDtoV1>(global::ClockifyClient.Models.UserSettingsDtoV1.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetObjectValue<global::ClockifyClient.Models.AccountStatus>(global::ClockifyClient.Models.AccountStatus.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("activeWorkspace", ActiveWorkspace);
            writer.WriteCollectionOfObjectValues<global::ClockifyClient.Models.UserCustomFieldValueDtoV1>("customFields", CustomFields);
            writer.WriteStringValue("defaultWorkspace", DefaultWorkspace);
            writer.WriteStringValue("email", Email);
            writer.WriteStringValue("id", Id);
            writer.WriteCollectionOfObjectValues<global::ClockifyClient.Models.MembershipDtoV1>("memberships", Memberships);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("profilePicture", ProfilePicture);
            writer.WriteObjectValue<global::ClockifyClient.Models.UserSettingsDtoV1>("settings", Settings);
            writer.WriteObjectValue<global::ClockifyClient.Models.AccountStatus>("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
