// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ClockifyClient.Models
{
    /// <summary>
    /// Represents a list of value objects for user’s custom fields.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UserCustomFieldValueFullDtoV1 : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The customField property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ClockifyClient.Models.CustomFieldDtoV1? CustomField { get; set; }
#nullable restore
#else
        public global::ClockifyClient.Models.CustomFieldDtoV1 CustomField { get; set; }
#endif
        /// <summary>Represents custom field identifier across the system.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomFieldId { get; set; }
#nullable restore
#else
        public string CustomFieldId { get; set; }
#endif
        /// <summary>Represents user custom field name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Represents user custom field source type.</summary>
        public global::ClockifyClient.Models.UserCustomFieldValueFullDtoV1_sourceType? SourceType { get; set; }
        /// <summary>Represents custom field type.</summary>
        public global::ClockifyClient.Models.UserCustomFieldValueFullDtoV1_type? Type { get; set; }
        /// <summary>Represents user identifier across the system.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserId { get; set; }
#nullable restore
#else
        public string UserId { get; set; }
#endif
        /// <summary>Represents user custom field value.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ClockifyClient.Models.UserCustomFieldValueFullDtoV1_value? Value { get; set; }
#nullable restore
#else
        public global::ClockifyClient.Models.UserCustomFieldValueFullDtoV1_value Value { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::ClockifyClient.Models.UserCustomFieldValueFullDtoV1"/> and sets the default values.
        /// </summary>
        public UserCustomFieldValueFullDtoV1()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ClockifyClient.Models.UserCustomFieldValueFullDtoV1"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ClockifyClient.Models.UserCustomFieldValueFullDtoV1 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::ClockifyClient.Models.UserCustomFieldValueFullDtoV1();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "customField", n => { CustomField = n.GetObjectValue<global::ClockifyClient.Models.CustomFieldDtoV1>(global::ClockifyClient.Models.CustomFieldDtoV1.CreateFromDiscriminatorValue); } },
                { "customFieldId", n => { CustomFieldId = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "sourceType", n => { SourceType = n.GetEnumValue<global::ClockifyClient.Models.UserCustomFieldValueFullDtoV1_sourceType>(); } },
                { "type", n => { Type = n.GetEnumValue<global::ClockifyClient.Models.UserCustomFieldValueFullDtoV1_type>(); } },
                { "userId", n => { UserId = n.GetStringValue(); } },
                { "value", n => { Value = n.GetObjectValue<global::ClockifyClient.Models.UserCustomFieldValueFullDtoV1_value>(global::ClockifyClient.Models.UserCustomFieldValueFullDtoV1_value.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::ClockifyClient.Models.CustomFieldDtoV1>("customField", CustomField);
            writer.WriteStringValue("customFieldId", CustomFieldId);
            writer.WriteStringValue("name", Name);
            writer.WriteEnumValue<global::ClockifyClient.Models.UserCustomFieldValueFullDtoV1_sourceType>("sourceType", SourceType);
            writer.WriteEnumValue<global::ClockifyClient.Models.UserCustomFieldValueFullDtoV1_type>("type", Type);
            writer.WriteStringValue("userId", UserId);
            writer.WriteObjectValue<global::ClockifyClient.Models.UserCustomFieldValueFullDtoV1_value>("value", Value);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
