// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ClockifyClient.Models
{
    /// <summary>
    /// Represents a webhook event trigger source type.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WebhookEventTriggerSourceType : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The ASSIGNMENT_ID property</summary>
        public global::ClockifyClient.Models.WebhookEventTriggerSourceType_ASSIGNMENT_ID? ASSIGNMENTID { get; set; }
        /// <summary>The entityType property</summary>
        public global::ClockifyClient.Models.WebhookEventTriggerSourceType_entityType? EntityType { get; set; }
        /// <summary>The EXPENSE_ID property</summary>
        public global::ClockifyClient.Models.WebhookEventTriggerSourceType_EXPENSE_ID? EXPENSEID { get; set; }
        /// <summary>The INVOICE_ID property</summary>
        public global::ClockifyClient.Models.WebhookEventTriggerSourceType_INVOICE_ID? INVOICEID { get; set; }
        /// <summary>The PROJECT_ID property</summary>
        public global::ClockifyClient.Models.WebhookEventTriggerSourceType_PROJECT_ID? PROJECTID { get; set; }
        /// <summary>The TAG_ID property</summary>
        public global::ClockifyClient.Models.WebhookEventTriggerSourceType_TAG_ID? TAGID { get; set; }
        /// <summary>The TASK_ID property</summary>
        public global::ClockifyClient.Models.WebhookEventTriggerSourceType_TASK_ID? TASKID { get; set; }
        /// <summary>The USER_GROUP_ID property</summary>
        public global::ClockifyClient.Models.WebhookEventTriggerSourceType_USER_GROUP_ID? USERGROUPID { get; set; }
        /// <summary>The USER_ID property</summary>
        public global::ClockifyClient.Models.WebhookEventTriggerSourceType_USER_ID? USERID { get; set; }
        /// <summary>The WORKSPACE_ID property</summary>
        public global::ClockifyClient.Models.WebhookEventTriggerSourceType_WORKSPACE_ID? WORKSPACEID { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::ClockifyClient.Models.WebhookEventTriggerSourceType"/> and sets the default values.
        /// </summary>
        public WebhookEventTriggerSourceType()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ClockifyClient.Models.WebhookEventTriggerSourceType"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ClockifyClient.Models.WebhookEventTriggerSourceType CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::ClockifyClient.Models.WebhookEventTriggerSourceType();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "ASSIGNMENT_ID", n => { ASSIGNMENTID = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventTriggerSourceType_ASSIGNMENT_ID>(); } },
                { "EXPENSE_ID", n => { EXPENSEID = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventTriggerSourceType_EXPENSE_ID>(); } },
                { "entityType", n => { EntityType = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventTriggerSourceType_entityType>(); } },
                { "INVOICE_ID", n => { INVOICEID = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventTriggerSourceType_INVOICE_ID>(); } },
                { "PROJECT_ID", n => { PROJECTID = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventTriggerSourceType_PROJECT_ID>(); } },
                { "TAG_ID", n => { TAGID = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventTriggerSourceType_TAG_ID>(); } },
                { "TASK_ID", n => { TASKID = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventTriggerSourceType_TASK_ID>(); } },
                { "USER_GROUP_ID", n => { USERGROUPID = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventTriggerSourceType_USER_GROUP_ID>(); } },
                { "USER_ID", n => { USERID = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventTriggerSourceType_USER_ID>(); } },
                { "WORKSPACE_ID", n => { WORKSPACEID = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventTriggerSourceType_WORKSPACE_ID>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventTriggerSourceType_ASSIGNMENT_ID>("ASSIGNMENT_ID", ASSIGNMENTID);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventTriggerSourceType_entityType>("entityType", EntityType);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventTriggerSourceType_EXPENSE_ID>("EXPENSE_ID", EXPENSEID);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventTriggerSourceType_INVOICE_ID>("INVOICE_ID", INVOICEID);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventTriggerSourceType_PROJECT_ID>("PROJECT_ID", PROJECTID);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventTriggerSourceType_TAG_ID>("TAG_ID", TAGID);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventTriggerSourceType_TASK_ID>("TASK_ID", TASKID);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventTriggerSourceType_USER_GROUP_ID>("USER_GROUP_ID", USERGROUPID);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventTriggerSourceType_USER_ID>("USER_ID", USERID);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventTriggerSourceType_WORKSPACE_ID>("WORKSPACE_ID", WORKSPACEID);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
