// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ClockifyClient.Models
{
    /// <summary>
    /// Represents webhook event type.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WebhookEventType : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The APPROVAL_REQUEST_STATUS_UPDATED property</summary>
        public global::ClockifyClient.Models.WebhookEventType_APPROVAL_REQUEST_STATUS_UPDATED? APPROVALREQUESTSTATUSUPDATED { get; set; }
        /// <summary>The ASSIGNMENT_CREATED property</summary>
        public global::ClockifyClient.Models.WebhookEventType_ASSIGNMENT_CREATED? ASSIGNMENTCREATED { get; set; }
        /// <summary>The ASSIGNMENT_DELETED property</summary>
        public global::ClockifyClient.Models.WebhookEventType_ASSIGNMENT_DELETED? ASSIGNMENTDELETED { get; set; }
        /// <summary>The ASSIGNMENT_PUBLISHED property</summary>
        public global::ClockifyClient.Models.WebhookEventType_ASSIGNMENT_PUBLISHED? ASSIGNMENTPUBLISHED { get; set; }
        /// <summary>The ASSIGNMENT_UPDATED property</summary>
        public global::ClockifyClient.Models.WebhookEventType_ASSIGNMENT_UPDATED? ASSIGNMENTUPDATED { get; set; }
        /// <summary>The BALANCE_UPDATED property</summary>
        public global::ClockifyClient.Models.WebhookEventType_BALANCE_UPDATED? BALANCEUPDATED { get; set; }
        /// <summary>The BILLABLE_RATE_UPDATED property</summary>
        public global::ClockifyClient.Models.WebhookEventType_BILLABLE_RATE_UPDATED? BILLABLERATEUPDATED { get; set; }
        /// <summary>The CLIENT_DELETED property</summary>
        public global::ClockifyClient.Models.WebhookEventType_CLIENT_DELETED? CLIENTDELETED { get; set; }
        /// <summary>The CLIENT_UPDATED property</summary>
        public global::ClockifyClient.Models.WebhookEventType_CLIENT_UPDATED? CLIENTUPDATED { get; set; }
        /// <summary>The COST_RATE_UPDATED property</summary>
        public global::ClockifyClient.Models.WebhookEventType_COST_RATE_UPDATED? COSTRATEUPDATED { get; set; }
        /// <summary>The EXPENSE_CREATED property</summary>
        public global::ClockifyClient.Models.WebhookEventType_EXPENSE_CREATED? EXPENSECREATED { get; set; }
        /// <summary>The EXPENSE_DELETED property</summary>
        public global::ClockifyClient.Models.WebhookEventType_EXPENSE_DELETED? EXPENSEDELETED { get; set; }
        /// <summary>The EXPENSE_RESTORED property</summary>
        public global::ClockifyClient.Models.WebhookEventType_EXPENSE_RESTORED? EXPENSERESTORED { get; set; }
        /// <summary>The EXPENSE_UPDATED property</summary>
        public global::ClockifyClient.Models.WebhookEventType_EXPENSE_UPDATED? EXPENSEUPDATED { get; set; }
        /// <summary>The feature property</summary>
        public global::ClockifyClient.Models.WebhookEventType_feature? Feature { get; set; }
        /// <summary>The INVOICE_UPDATED property</summary>
        public global::ClockifyClient.Models.WebhookEventType_INVOICE_UPDATED? INVOICEUPDATED { get; set; }
        /// <summary>The LIMITED_USERS_ADDED_TO_WORKSPACE property</summary>
        public global::ClockifyClient.Models.WebhookEventType_LIMITED_USERS_ADDED_TO_WORKSPACE? LIMITEDUSERSADDEDTOWORKSPACE { get; set; }
        /// <summary>The NEW_APPROVAL_REQUEST property</summary>
        public global::ClockifyClient.Models.WebhookEventType_NEW_APPROVAL_REQUEST? NEWAPPROVALREQUEST { get; set; }
        /// <summary>The NEW_CLIENT property</summary>
        public global::ClockifyClient.Models.WebhookEventType_NEW_CLIENT? NEWCLIENT { get; set; }
        /// <summary>The NEW_INVOICE property</summary>
        public global::ClockifyClient.Models.WebhookEventType_NEW_INVOICE? NEWINVOICE { get; set; }
        /// <summary>The NEW_PROJECT property</summary>
        public global::ClockifyClient.Models.WebhookEventType_NEW_PROJECT? NEWPROJECT { get; set; }
        /// <summary>The NEW_TAG property</summary>
        public global::ClockifyClient.Models.WebhookEventType_NEW_TAG? NEWTAG { get; set; }
        /// <summary>The NEW_TASK property</summary>
        public global::ClockifyClient.Models.WebhookEventType_NEW_TASK? NEWTASK { get; set; }
        /// <summary>The NEW_TIME_ENTRY property</summary>
        public global::ClockifyClient.Models.WebhookEventType_NEW_TIME_ENTRY? NEWTIMEENTRY { get; set; }
        /// <summary>The NEW_TIMER_STARTED property</summary>
        public global::ClockifyClient.Models.WebhookEventType_NEW_TIMER_STARTED? NEWTIMERSTARTED { get; set; }
        /// <summary>The payloadType property</summary>
        public global::ClockifyClient.Models.WebhookEventType_payloadType? PayloadType { get; set; }
        /// <summary>The PROJECT_DELETED property</summary>
        public global::ClockifyClient.Models.WebhookEventType_PROJECT_DELETED? PROJECTDELETED { get; set; }
        /// <summary>The PROJECT_UPDATED property</summary>
        public global::ClockifyClient.Models.WebhookEventType_PROJECT_UPDATED? PROJECTUPDATED { get; set; }
        /// <summary>The TAG_DELETED property</summary>
        public global::ClockifyClient.Models.WebhookEventType_TAG_DELETED? TAGDELETED { get; set; }
        /// <summary>The TAG_UPDATED property</summary>
        public global::ClockifyClient.Models.WebhookEventType_TAG_UPDATED? TAGUPDATED { get; set; }
        /// <summary>The TASK_DELETED property</summary>
        public global::ClockifyClient.Models.WebhookEventType_TASK_DELETED? TASKDELETED { get; set; }
        /// <summary>The TASK_UPDATED property</summary>
        public global::ClockifyClient.Models.WebhookEventType_TASK_UPDATED? TASKUPDATED { get; set; }
        /// <summary>The TIME_ENTRY_DELETED property</summary>
        public global::ClockifyClient.Models.WebhookEventType_TIME_ENTRY_DELETED? TIMEENTRYDELETED { get; set; }
        /// <summary>The TIME_ENTRY_RESTORED property</summary>
        public global::ClockifyClient.Models.WebhookEventType_TIME_ENTRY_RESTORED? TIMEENTRYRESTORED { get; set; }
        /// <summary>The TIME_ENTRY_SPLIT property</summary>
        public global::ClockifyClient.Models.WebhookEventType_TIME_ENTRY_SPLIT? TIMEENTRYSPLIT { get; set; }
        /// <summary>The TIME_ENTRY_UPDATED property</summary>
        public global::ClockifyClient.Models.WebhookEventType_TIME_ENTRY_UPDATED? TIMEENTRYUPDATED { get; set; }
        /// <summary>The TIME_OFF_REQUEST_APPROVED property</summary>
        public global::ClockifyClient.Models.WebhookEventType_TIME_OFF_REQUEST_APPROVED? TIMEOFFREQUESTAPPROVED { get; set; }
        /// <summary>The TIME_OFF_REQUESTED property</summary>
        public global::ClockifyClient.Models.WebhookEventType_TIME_OFF_REQUESTED? TIMEOFFREQUESTED { get; set; }
        /// <summary>The TIME_OFF_REQUEST_REJECTED property</summary>
        public global::ClockifyClient.Models.WebhookEventType_TIME_OFF_REQUEST_REJECTED? TIMEOFFREQUESTREJECTED { get; set; }
        /// <summary>The TIME_OFF_REQUEST_UPDATED property</summary>
        public global::ClockifyClient.Models.WebhookEventType_TIME_OFF_REQUEST_UPDATED? TIMEOFFREQUESTUPDATED { get; set; }
        /// <summary>The TIME_OFF_REQUEST_WITHDRAWN property</summary>
        public global::ClockifyClient.Models.WebhookEventType_TIME_OFF_REQUEST_WITHDRAWN? TIMEOFFREQUESTWITHDRAWN { get; set; }
        /// <summary>The TIMER_STOPPED property</summary>
        public global::ClockifyClient.Models.WebhookEventType_TIMER_STOPPED? TIMERSTOPPED { get; set; }
        /// <summary>The USER_ACTIVATED_ON_WORKSPACE property</summary>
        public global::ClockifyClient.Models.WebhookEventType_USER_ACTIVATED_ON_WORKSPACE? USERACTIVATEDONWORKSPACE { get; set; }
        /// <summary>The USER_DEACTIVATED_ON_WORKSPACE property</summary>
        public global::ClockifyClient.Models.WebhookEventType_USER_DEACTIVATED_ON_WORKSPACE? USERDEACTIVATEDONWORKSPACE { get; set; }
        /// <summary>The USER_DELETED_FROM_WORKSPACE property</summary>
        public global::ClockifyClient.Models.WebhookEventType_USER_DELETED_FROM_WORKSPACE? USERDELETEDFROMWORKSPACE { get; set; }
        /// <summary>The USER_EMAIL_CHANGED property</summary>
        public global::ClockifyClient.Models.WebhookEventType_USER_EMAIL_CHANGED? USEREMAILCHANGED { get; set; }
        /// <summary>The USER_GROUP_CREATED property</summary>
        public global::ClockifyClient.Models.WebhookEventType_USER_GROUP_CREATED? USERGROUPCREATED { get; set; }
        /// <summary>The USER_GROUP_DELETED property</summary>
        public global::ClockifyClient.Models.WebhookEventType_USER_GROUP_DELETED? USERGROUPDELETED { get; set; }
        /// <summary>The USER_GROUP_UPDATED property</summary>
        public global::ClockifyClient.Models.WebhookEventType_USER_GROUP_UPDATED? USERGROUPUPDATED { get; set; }
        /// <summary>The USER_JOINED_WORKSPACE property</summary>
        public global::ClockifyClient.Models.WebhookEventType_USER_JOINED_WORKSPACE? USERJOINEDWORKSPACE { get; set; }
        /// <summary>The USERS_INVITED_TO_WORKSPACE property</summary>
        public global::ClockifyClient.Models.WebhookEventType_USERS_INVITED_TO_WORKSPACE? USERSINVITEDTOWORKSPACE { get; set; }
        /// <summary>The USER_UPDATED property</summary>
        public global::ClockifyClient.Models.WebhookEventType_USER_UPDATED? USERUPDATED { get; set; }
        /// <summary>The validSourceTypes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::ClockifyClient.Models.WebhookEventType_validSourceTypes?>? ValidSourceTypes { get; set; }
#nullable restore
#else
        public List<global::ClockifyClient.Models.WebhookEventType_validSourceTypes?> ValidSourceTypes { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::ClockifyClient.Models.WebhookEventType"/> and sets the default values.
        /// </summary>
        public WebhookEventType()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ClockifyClient.Models.WebhookEventType"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ClockifyClient.Models.WebhookEventType CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ClockifyClient.Models.WebhookEventType();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "APPROVAL_REQUEST_STATUS_UPDATED", n => { APPROVALREQUESTSTATUSUPDATED = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventType_APPROVAL_REQUEST_STATUS_UPDATED>(); } },
                { "ASSIGNMENT_CREATED", n => { ASSIGNMENTCREATED = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventType_ASSIGNMENT_CREATED>(); } },
                { "ASSIGNMENT_DELETED", n => { ASSIGNMENTDELETED = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventType_ASSIGNMENT_DELETED>(); } },
                { "ASSIGNMENT_PUBLISHED", n => { ASSIGNMENTPUBLISHED = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventType_ASSIGNMENT_PUBLISHED>(); } },
                { "ASSIGNMENT_UPDATED", n => { ASSIGNMENTUPDATED = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventType_ASSIGNMENT_UPDATED>(); } },
                { "BALANCE_UPDATED", n => { BALANCEUPDATED = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventType_BALANCE_UPDATED>(); } },
                { "BILLABLE_RATE_UPDATED", n => { BILLABLERATEUPDATED = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventType_BILLABLE_RATE_UPDATED>(); } },
                { "CLIENT_DELETED", n => { CLIENTDELETED = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventType_CLIENT_DELETED>(); } },
                { "CLIENT_UPDATED", n => { CLIENTUPDATED = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventType_CLIENT_UPDATED>(); } },
                { "COST_RATE_UPDATED", n => { COSTRATEUPDATED = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventType_COST_RATE_UPDATED>(); } },
                { "EXPENSE_CREATED", n => { EXPENSECREATED = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventType_EXPENSE_CREATED>(); } },
                { "EXPENSE_DELETED", n => { EXPENSEDELETED = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventType_EXPENSE_DELETED>(); } },
                { "EXPENSE_RESTORED", n => { EXPENSERESTORED = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventType_EXPENSE_RESTORED>(); } },
                { "EXPENSE_UPDATED", n => { EXPENSEUPDATED = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventType_EXPENSE_UPDATED>(); } },
                { "feature", n => { Feature = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventType_feature>(); } },
                { "INVOICE_UPDATED", n => { INVOICEUPDATED = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventType_INVOICE_UPDATED>(); } },
                { "LIMITED_USERS_ADDED_TO_WORKSPACE", n => { LIMITEDUSERSADDEDTOWORKSPACE = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventType_LIMITED_USERS_ADDED_TO_WORKSPACE>(); } },
                { "NEW_APPROVAL_REQUEST", n => { NEWAPPROVALREQUEST = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventType_NEW_APPROVAL_REQUEST>(); } },
                { "NEW_CLIENT", n => { NEWCLIENT = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventType_NEW_CLIENT>(); } },
                { "NEW_INVOICE", n => { NEWINVOICE = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventType_NEW_INVOICE>(); } },
                { "NEW_PROJECT", n => { NEWPROJECT = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventType_NEW_PROJECT>(); } },
                { "NEW_TAG", n => { NEWTAG = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventType_NEW_TAG>(); } },
                { "NEW_TASK", n => { NEWTASK = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventType_NEW_TASK>(); } },
                { "NEW_TIME_ENTRY", n => { NEWTIMEENTRY = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventType_NEW_TIME_ENTRY>(); } },
                { "NEW_TIMER_STARTED", n => { NEWTIMERSTARTED = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventType_NEW_TIMER_STARTED>(); } },
                { "PROJECT_DELETED", n => { PROJECTDELETED = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventType_PROJECT_DELETED>(); } },
                { "PROJECT_UPDATED", n => { PROJECTUPDATED = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventType_PROJECT_UPDATED>(); } },
                { "payloadType", n => { PayloadType = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventType_payloadType>(); } },
                { "TAG_DELETED", n => { TAGDELETED = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventType_TAG_DELETED>(); } },
                { "TAG_UPDATED", n => { TAGUPDATED = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventType_TAG_UPDATED>(); } },
                { "TASK_DELETED", n => { TASKDELETED = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventType_TASK_DELETED>(); } },
                { "TASK_UPDATED", n => { TASKUPDATED = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventType_TASK_UPDATED>(); } },
                { "TIME_ENTRY_DELETED", n => { TIMEENTRYDELETED = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventType_TIME_ENTRY_DELETED>(); } },
                { "TIME_ENTRY_RESTORED", n => { TIMEENTRYRESTORED = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventType_TIME_ENTRY_RESTORED>(); } },
                { "TIME_ENTRY_SPLIT", n => { TIMEENTRYSPLIT = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventType_TIME_ENTRY_SPLIT>(); } },
                { "TIME_ENTRY_UPDATED", n => { TIMEENTRYUPDATED = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventType_TIME_ENTRY_UPDATED>(); } },
                { "TIME_OFF_REQUEST_APPROVED", n => { TIMEOFFREQUESTAPPROVED = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventType_TIME_OFF_REQUEST_APPROVED>(); } },
                { "TIME_OFF_REQUESTED", n => { TIMEOFFREQUESTED = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventType_TIME_OFF_REQUESTED>(); } },
                { "TIME_OFF_REQUEST_REJECTED", n => { TIMEOFFREQUESTREJECTED = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventType_TIME_OFF_REQUEST_REJECTED>(); } },
                { "TIME_OFF_REQUEST_UPDATED", n => { TIMEOFFREQUESTUPDATED = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventType_TIME_OFF_REQUEST_UPDATED>(); } },
                { "TIME_OFF_REQUEST_WITHDRAWN", n => { TIMEOFFREQUESTWITHDRAWN = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventType_TIME_OFF_REQUEST_WITHDRAWN>(); } },
                { "TIMER_STOPPED", n => { TIMERSTOPPED = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventType_TIMER_STOPPED>(); } },
                { "USER_ACTIVATED_ON_WORKSPACE", n => { USERACTIVATEDONWORKSPACE = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventType_USER_ACTIVATED_ON_WORKSPACE>(); } },
                { "USER_DEACTIVATED_ON_WORKSPACE", n => { USERDEACTIVATEDONWORKSPACE = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventType_USER_DEACTIVATED_ON_WORKSPACE>(); } },
                { "USER_DELETED_FROM_WORKSPACE", n => { USERDELETEDFROMWORKSPACE = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventType_USER_DELETED_FROM_WORKSPACE>(); } },
                { "USER_EMAIL_CHANGED", n => { USEREMAILCHANGED = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventType_USER_EMAIL_CHANGED>(); } },
                { "USER_GROUP_CREATED", n => { USERGROUPCREATED = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventType_USER_GROUP_CREATED>(); } },
                { "USER_GROUP_DELETED", n => { USERGROUPDELETED = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventType_USER_GROUP_DELETED>(); } },
                { "USER_GROUP_UPDATED", n => { USERGROUPUPDATED = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventType_USER_GROUP_UPDATED>(); } },
                { "USER_JOINED_WORKSPACE", n => { USERJOINEDWORKSPACE = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventType_USER_JOINED_WORKSPACE>(); } },
                { "USERS_INVITED_TO_WORKSPACE", n => { USERSINVITEDTOWORKSPACE = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventType_USERS_INVITED_TO_WORKSPACE>(); } },
                { "USER_UPDATED", n => { USERUPDATED = n.GetEnumValue<global::ClockifyClient.Models.WebhookEventType_USER_UPDATED>(); } },
                { "validSourceTypes", n => { ValidSourceTypes = n.GetCollectionOfEnumValues<global::ClockifyClient.Models.WebhookEventType_validSourceTypes>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventType_APPROVAL_REQUEST_STATUS_UPDATED>("APPROVAL_REQUEST_STATUS_UPDATED", APPROVALREQUESTSTATUSUPDATED);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventType_ASSIGNMENT_CREATED>("ASSIGNMENT_CREATED", ASSIGNMENTCREATED);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventType_ASSIGNMENT_DELETED>("ASSIGNMENT_DELETED", ASSIGNMENTDELETED);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventType_ASSIGNMENT_PUBLISHED>("ASSIGNMENT_PUBLISHED", ASSIGNMENTPUBLISHED);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventType_ASSIGNMENT_UPDATED>("ASSIGNMENT_UPDATED", ASSIGNMENTUPDATED);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventType_BALANCE_UPDATED>("BALANCE_UPDATED", BALANCEUPDATED);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventType_BILLABLE_RATE_UPDATED>("BILLABLE_RATE_UPDATED", BILLABLERATEUPDATED);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventType_CLIENT_DELETED>("CLIENT_DELETED", CLIENTDELETED);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventType_CLIENT_UPDATED>("CLIENT_UPDATED", CLIENTUPDATED);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventType_COST_RATE_UPDATED>("COST_RATE_UPDATED", COSTRATEUPDATED);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventType_EXPENSE_CREATED>("EXPENSE_CREATED", EXPENSECREATED);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventType_EXPENSE_DELETED>("EXPENSE_DELETED", EXPENSEDELETED);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventType_EXPENSE_RESTORED>("EXPENSE_RESTORED", EXPENSERESTORED);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventType_EXPENSE_UPDATED>("EXPENSE_UPDATED", EXPENSEUPDATED);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventType_feature>("feature", Feature);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventType_INVOICE_UPDATED>("INVOICE_UPDATED", INVOICEUPDATED);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventType_LIMITED_USERS_ADDED_TO_WORKSPACE>("LIMITED_USERS_ADDED_TO_WORKSPACE", LIMITEDUSERSADDEDTOWORKSPACE);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventType_NEW_APPROVAL_REQUEST>("NEW_APPROVAL_REQUEST", NEWAPPROVALREQUEST);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventType_NEW_CLIENT>("NEW_CLIENT", NEWCLIENT);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventType_NEW_INVOICE>("NEW_INVOICE", NEWINVOICE);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventType_NEW_PROJECT>("NEW_PROJECT", NEWPROJECT);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventType_NEW_TAG>("NEW_TAG", NEWTAG);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventType_NEW_TASK>("NEW_TASK", NEWTASK);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventType_NEW_TIME_ENTRY>("NEW_TIME_ENTRY", NEWTIMEENTRY);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventType_NEW_TIMER_STARTED>("NEW_TIMER_STARTED", NEWTIMERSTARTED);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventType_payloadType>("payloadType", PayloadType);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventType_PROJECT_DELETED>("PROJECT_DELETED", PROJECTDELETED);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventType_PROJECT_UPDATED>("PROJECT_UPDATED", PROJECTUPDATED);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventType_TAG_DELETED>("TAG_DELETED", TAGDELETED);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventType_TAG_UPDATED>("TAG_UPDATED", TAGUPDATED);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventType_TASK_DELETED>("TASK_DELETED", TASKDELETED);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventType_TASK_UPDATED>("TASK_UPDATED", TASKUPDATED);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventType_TIME_ENTRY_DELETED>("TIME_ENTRY_DELETED", TIMEENTRYDELETED);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventType_TIME_ENTRY_RESTORED>("TIME_ENTRY_RESTORED", TIMEENTRYRESTORED);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventType_TIME_ENTRY_SPLIT>("TIME_ENTRY_SPLIT", TIMEENTRYSPLIT);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventType_TIME_ENTRY_UPDATED>("TIME_ENTRY_UPDATED", TIMEENTRYUPDATED);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventType_TIME_OFF_REQUEST_APPROVED>("TIME_OFF_REQUEST_APPROVED", TIMEOFFREQUESTAPPROVED);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventType_TIME_OFF_REQUESTED>("TIME_OFF_REQUESTED", TIMEOFFREQUESTED);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventType_TIME_OFF_REQUEST_REJECTED>("TIME_OFF_REQUEST_REJECTED", TIMEOFFREQUESTREJECTED);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventType_TIME_OFF_REQUEST_UPDATED>("TIME_OFF_REQUEST_UPDATED", TIMEOFFREQUESTUPDATED);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventType_TIME_OFF_REQUEST_WITHDRAWN>("TIME_OFF_REQUEST_WITHDRAWN", TIMEOFFREQUESTWITHDRAWN);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventType_TIMER_STOPPED>("TIMER_STOPPED", TIMERSTOPPED);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventType_USER_ACTIVATED_ON_WORKSPACE>("USER_ACTIVATED_ON_WORKSPACE", USERACTIVATEDONWORKSPACE);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventType_USER_DEACTIVATED_ON_WORKSPACE>("USER_DEACTIVATED_ON_WORKSPACE", USERDEACTIVATEDONWORKSPACE);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventType_USER_DELETED_FROM_WORKSPACE>("USER_DELETED_FROM_WORKSPACE", USERDELETEDFROMWORKSPACE);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventType_USER_EMAIL_CHANGED>("USER_EMAIL_CHANGED", USEREMAILCHANGED);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventType_USER_GROUP_CREATED>("USER_GROUP_CREATED", USERGROUPCREATED);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventType_USER_GROUP_DELETED>("USER_GROUP_DELETED", USERGROUPDELETED);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventType_USER_GROUP_UPDATED>("USER_GROUP_UPDATED", USERGROUPUPDATED);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventType_USER_JOINED_WORKSPACE>("USER_JOINED_WORKSPACE", USERJOINEDWORKSPACE);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventType_USERS_INVITED_TO_WORKSPACE>("USERS_INVITED_TO_WORKSPACE", USERSINVITEDTOWORKSPACE);
            writer.WriteEnumValue<global::ClockifyClient.Models.WebhookEventType_USER_UPDATED>("USER_UPDATED", USERUPDATED);
            writer.WriteCollectionOfEnumValues<global::ClockifyClient.Models.WebhookEventType_validSourceTypes>("validSourceTypes", ValidSourceTypes);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
