// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ClockifyClient.Models
{
    /// <summary>Represents a clockify number format enum.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WorkspaceSettingsDtoV1_numberFormat
    {
        [EnumMember(Value = "COMMA_PERIOD")]
        #pragma warning disable CS1591
        COMMA_PERIOD,
        #pragma warning restore CS1591
        [EnumMember(Value = "PERIOD_COMMA")]
        #pragma warning disable CS1591
        PERIOD_COMMA,
        #pragma warning restore CS1591
        [EnumMember(Value = "QUOTATION_MARK_PERIOD")]
        #pragma warning disable CS1591
        QUOTATION_MARK_PERIOD,
        #pragma warning restore CS1591
        [EnumMember(Value = "SPACE_COMMA")]
        #pragma warning disable CS1591
        SPACE_COMMA,
        #pragma warning restore CS1591
    }
}
