// <auto-generated/>
#pragma warning disable CS0618
using ClockifyClient.V1.Workspaces.Item.Scheduling.Assignments.All;
using ClockifyClient.V1.Workspaces.Item.Scheduling.Assignments.Item;
using ClockifyClient.V1.Workspaces.Item.Scheduling.Assignments.Projects;
using ClockifyClient.V1.Workspaces.Item.Scheduling.Assignments.Publish;
using ClockifyClient.V1.Workspaces.Item.Scheduling.Assignments.Recurring;
using ClockifyClient.V1.Workspaces.Item.Scheduling.Assignments.Series;
using ClockifyClient.V1.Workspaces.Item.Scheduling.Assignments.UserFilter;
using ClockifyClient.V1.Workspaces.Item.Scheduling.Assignments.Users;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ClockifyClient.V1.Workspaces.Item.Scheduling.Assignments
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\workspaces\{workspaceId}\scheduling\assignments
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AssignmentsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The all property</summary>
        public global::ClockifyClient.V1.Workspaces.Item.Scheduling.Assignments.All.AllRequestBuilder All
        {
            get => new global::ClockifyClient.V1.Workspaces.Item.Scheduling.Assignments.All.AllRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The projects property</summary>
        public global::ClockifyClient.V1.Workspaces.Item.Scheduling.Assignments.Projects.ProjectsRequestBuilder Projects
        {
            get => new global::ClockifyClient.V1.Workspaces.Item.Scheduling.Assignments.Projects.ProjectsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The publish property</summary>
        public global::ClockifyClient.V1.Workspaces.Item.Scheduling.Assignments.Publish.PublishRequestBuilder Publish
        {
            get => new global::ClockifyClient.V1.Workspaces.Item.Scheduling.Assignments.Publish.PublishRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The recurring property</summary>
        public global::ClockifyClient.V1.Workspaces.Item.Scheduling.Assignments.Recurring.RecurringRequestBuilder Recurring
        {
            get => new global::ClockifyClient.V1.Workspaces.Item.Scheduling.Assignments.Recurring.RecurringRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The series property</summary>
        public global::ClockifyClient.V1.Workspaces.Item.Scheduling.Assignments.Series.SeriesRequestBuilder Series
        {
            get => new global::ClockifyClient.V1.Workspaces.Item.Scheduling.Assignments.Series.SeriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The userFilter property</summary>
        public global::ClockifyClient.V1.Workspaces.Item.Scheduling.Assignments.UserFilter.UserFilterRequestBuilder UserFilter
        {
            get => new global::ClockifyClient.V1.Workspaces.Item.Scheduling.Assignments.UserFilter.UserFilterRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::ClockifyClient.V1.Workspaces.Item.Scheduling.Assignments.Users.UsersRequestBuilder Users
        {
            get => new global::ClockifyClient.V1.Workspaces.Item.Scheduling.Assignments.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the ClockifyClient.v1.workspaces.item.scheduling.assignments.item collection</summary>
        /// <param name="position">Represents assignment identifier across the system.</param>
        /// <returns>A <see cref="global::ClockifyClient.V1.Workspaces.Item.Scheduling.Assignments.Item.WithAssignmentItemRequestBuilder"/></returns>
        public global::ClockifyClient.V1.Workspaces.Item.Scheduling.Assignments.Item.WithAssignmentItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("assignmentId", position);
                return new global::ClockifyClient.V1.Workspaces.Item.Scheduling.Assignments.Item.WithAssignmentItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ClockifyClient.V1.Workspaces.Item.Scheduling.Assignments.AssignmentsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AssignmentsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/workspaces/{workspaceId}/scheduling/assignments", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ClockifyClient.V1.Workspaces.Item.Scheduling.Assignments.AssignmentsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AssignmentsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/workspaces/{workspaceId}/scheduling/assignments", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
