// <auto-generated/>
#pragma warning disable CS0618
using ClockifyClient.V1.Workspaces.Item.User.Item.TimeEntries.Item.Duplicate;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ClockifyClient.V1.Workspaces.Item.User.Item.TimeEntries.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\workspaces\{workspaceId}\user\{userId}\time-entries\{id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TimeEntriesItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The duplicate property</summary>
        public global::ClockifyClient.V1.Workspaces.Item.User.Item.TimeEntries.Item.Duplicate.DuplicateRequestBuilder Duplicate
        {
            get => new global::ClockifyClient.V1.Workspaces.Item.User.Item.TimeEntries.Item.Duplicate.DuplicateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ClockifyClient.V1.Workspaces.Item.User.Item.TimeEntries.Item.TimeEntriesItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TimeEntriesItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/workspaces/{workspaceId}/user/{userId}/time-entries/{id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ClockifyClient.V1.Workspaces.Item.User.Item.TimeEntries.Item.TimeEntriesItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TimeEntriesItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/workspaces/{workspaceId}/user/{userId}/time-entries/{id}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
