// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ClockifyClient.V1.Workspaces
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetRolesQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "WORKSPACE_ADMIN")]
        #pragma warning disable CS1591
        WORKSPACE_ADMIN,
        #pragma warning restore CS1591
        [EnumMember(Value = "OWNER")]
        #pragma warning disable CS1591
        OWNER,
        #pragma warning restore CS1591
        [EnumMember(Value = "TEAM_MANAGER")]
        #pragma warning disable CS1591
        TEAM_MANAGER,
        #pragma warning restore CS1591
        [EnumMember(Value = "PROJECT_MANAGER")]
        #pragma warning disable CS1591
        PROJECT_MANAGER,
        #pragma warning restore CS1591
    }
}
