// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ClockifyClient.V1.Workspaces.Item.Projects
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetClientStatusQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "ACTIVE")]
        #pragma warning disable CS1591
        ACTIVE,
        #pragma warning restore CS1591
        [EnumMember(Value = "ARCHIVED")]
        #pragma warning disable CS1591
        ARCHIVED,
        #pragma warning restore CS1591
        [EnumMember(Value = "ALL")]
        #pragma warning disable CS1591
        ALL,
        #pragma warning restore CS1591
    }
}
