// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ClockifyClient.V1.Workspaces.Item.Projects
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetSortColumnQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "ID")]
        #pragma warning disable CS1591
        ID,
        #pragma warning restore CS1591
        [EnumMember(Value = "NAME")]
        #pragma warning disable CS1591
        NAME,
        #pragma warning restore CS1591
        [EnumMember(Value = "CLIENT_NAME")]
        #pragma warning disable CS1591
        CLIENT_NAME,
        #pragma warning restore CS1591
        [EnumMember(Value = "DURATION")]
        #pragma warning disable CS1591
        DURATION,
        #pragma warning restore CS1591
        [EnumMember(Value = "BUDGET")]
        #pragma warning disable CS1591
        BUDGET,
        #pragma warning restore CS1591
        [EnumMember(Value = "PROGRESS")]
        #pragma warning disable CS1591
        PROGRESS,
        #pragma warning restore CS1591
    }
}
