// <auto-generated/>
#pragma warning disable CS0618
using ClockifyClient.Models;
using ClockifyClient.V1.Workspaces.Item.ApprovalRequests.Item;
using ClockifyClient.V1.Workspaces.Item.ApprovalRequests.ResubmitEntriesForApproval;
using ClockifyClient.V1.Workspaces.Item.ApprovalRequests.Users;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace ClockifyClient.V1.Workspaces.Item.ApprovalRequests
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\workspaces\{workspaceId}\approval-requests
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApprovalRequestsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The resubmitEntriesForApproval property</summary>
        public global::ClockifyClient.V1.Workspaces.Item.ApprovalRequests.ResubmitEntriesForApproval.ResubmitEntriesForApprovalRequestBuilder ResubmitEntriesForApproval
        {
            get => new global::ClockifyClient.V1.Workspaces.Item.ApprovalRequests.ResubmitEntriesForApproval.ResubmitEntriesForApprovalRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::ClockifyClient.V1.Workspaces.Item.ApprovalRequests.Users.UsersRequestBuilder Users
        {
            get => new global::ClockifyClient.V1.Workspaces.Item.ApprovalRequests.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the ClockifyClient.v1.workspaces.item.approvalRequests.item collection</summary>
        /// <param name="position">Represents approval request identifier across the system.</param>
        /// <returns>A <see cref="global::ClockifyClient.V1.Workspaces.Item.ApprovalRequests.Item.WithApprovalRequestItemRequestBuilder"/></returns>
        public global::ClockifyClient.V1.Workspaces.Item.ApprovalRequests.Item.WithApprovalRequestItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("approvalRequestId", position);
                return new global::ClockifyClient.V1.Workspaces.Item.ApprovalRequests.Item.WithApprovalRequestItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ClockifyClient.V1.Workspaces.Item.ApprovalRequests.ApprovalRequestsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApprovalRequestsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/workspaces/{workspaceId}/approval-requests{?page*,page%2Dsize*,sort%2Dcolumn*,sort%2Dorder*,status*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ClockifyClient.V1.Workspaces.Item.ApprovalRequests.ApprovalRequestsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApprovalRequestsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/workspaces/{workspaceId}/approval-requests{?page*,page%2Dsize*,sort%2Dcolumn*,sort%2Dorder*,status*}", rawUrl)
        {
        }
        /// <summary>
        /// Get approval requests
        /// </summary>
        /// <returns>A List&lt;global::ClockifyClient.Models.ApprovalDetailsDtoV1&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::ClockifyClient.Models.ApprovalDetailsDtoV1>?> GetAsync(Action<RequestConfiguration<global::ClockifyClient.V1.Workspaces.Item.ApprovalRequests.ApprovalRequestsRequestBuilder.ApprovalRequestsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::ClockifyClient.Models.ApprovalDetailsDtoV1>> GetAsync(Action<RequestConfiguration<global::ClockifyClient.V1.Workspaces.Item.ApprovalRequests.ApprovalRequestsRequestBuilder.ApprovalRequestsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::ClockifyClient.Models.ApprovalDetailsDtoV1>(requestInfo, global::ClockifyClient.Models.ApprovalDetailsDtoV1.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Submit approval request
        /// </summary>
        /// <returns>A <see cref="global::ClockifyClient.Models.ApprovalRequestDtoV1"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::ClockifyClient.Models.ApprovalRequestDtoV1?> PostAsync(global::ClockifyClient.Models.CreateApprovalRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::ClockifyClient.Models.ApprovalRequestDtoV1> PostAsync(global::ClockifyClient.Models.CreateApprovalRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::ClockifyClient.Models.ApprovalRequestDtoV1>(requestInfo, global::ClockifyClient.Models.ApprovalRequestDtoV1.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get approval requests
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::ClockifyClient.V1.Workspaces.Item.ApprovalRequests.ApprovalRequestsRequestBuilder.ApprovalRequestsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::ClockifyClient.V1.Workspaces.Item.ApprovalRequests.ApprovalRequestsRequestBuilder.ApprovalRequestsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Submit approval request
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::ClockifyClient.Models.CreateApprovalRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::ClockifyClient.Models.CreateApprovalRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::ClockifyClient.V1.Workspaces.Item.ApprovalRequests.ApprovalRequestsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::ClockifyClient.V1.Workspaces.Item.ApprovalRequests.ApprovalRequestsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::ClockifyClient.V1.Workspaces.Item.ApprovalRequests.ApprovalRequestsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get approval requests
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ApprovalRequestsRequestBuilderGetQueryParameters 
        {
            /// <summary>Page number.</summary>
            [QueryParameter("page")]
            public int? Page { get; set; }
            /// <summary>Page size.</summary>
            [QueryParameter("page%2Dsize")]
            public int? PageSize { get; set; }
            /// <summary>Represents the column name to be used as sorting criteria.</summary>
            [Obsolete("This property is deprecated, use SortColumnAsGetSortColumnQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sort%2Dcolumn")]
            public string? SortColumn { get; set; }
#nullable restore
#else
            [QueryParameter("sort%2Dcolumn")]
            public string SortColumn { get; set; }
#endif
            /// <summary>Represents the column name to be used as sorting criteria.</summary>
            [QueryParameter("sort%2Dcolumn")]
            public global::ClockifyClient.V1.Workspaces.Item.ApprovalRequests.GetSortColumnQueryParameterType? SortColumnAsGetSortColumnQueryParameterType { get; set; }
            /// <summary>Represents the sorting order.</summary>
            [Obsolete("This property is deprecated, use SortOrderAsGetSortOrderQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sort%2Dorder")]
            public string? SortOrder { get; set; }
#nullable restore
#else
            [QueryParameter("sort%2Dorder")]
            public string SortOrder { get; set; }
#endif
            /// <summary>Represents the sorting order.</summary>
            [QueryParameter("sort%2Dorder")]
            public global::ClockifyClient.V1.Workspaces.Item.ApprovalRequests.GetSortOrderQueryParameterType? SortOrderAsGetSortOrderQueryParameterType { get; set; }
            /// <summary>Filters results based from the provided approval state.</summary>
            [Obsolete("This property is deprecated, use StatusAsGetStatusQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("status")]
            public string? Status { get; set; }
#nullable restore
#else
            [QueryParameter("status")]
            public string Status { get; set; }
#endif
            /// <summary>Filters results based from the provided approval state.</summary>
            [QueryParameter("status")]
            public global::ClockifyClient.V1.Workspaces.Item.ApprovalRequests.GetStatusQueryParameterType? StatusAsGetStatusQueryParameterType { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ApprovalRequestsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::ClockifyClient.V1.Workspaces.Item.ApprovalRequests.ApprovalRequestsRequestBuilder.ApprovalRequestsRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ApprovalRequestsRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
