// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ClockifyClient.V1.Workspaces.Item.Scheduling.Assignments.Recurring.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum DeleteSeriesUpdateOptionQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "THIS_ONE")]
        #pragma warning disable CS1591
        THIS_ONE,
        #pragma warning restore CS1591
        [EnumMember(Value = "THIS_AND_FOLLOWING")]
        #pragma warning disable CS1591
        THIS_AND_FOLLOWING,
        #pragma warning restore CS1591
        [EnumMember(Value = "ALL")]
        #pragma warning disable CS1591
        ALL,
        #pragma warning restore CS1591
    }
}
