// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ClockifyClient.V1.Workspaces.Item.Projects.Item.Tasks
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetSortColumnQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "ID")]
        #pragma warning disable CS1591
        ID,
        #pragma warning restore CS1591
        [EnumMember(Value = "NAME")]
        #pragma warning disable CS1591
        NAME,
        #pragma warning restore CS1591
    }
}
