// <auto-generated/>
#pragma warning disable CS0618
using ClockifyClient.V1.Workspaces.Item.TimeEntries.Status.InProgress;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ClockifyClient.V1.Workspaces.Item.TimeEntries.Status
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\workspaces\{workspaceId}\time-entries\status
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StatusRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The inProgress property</summary>
        public global::ClockifyClient.V1.Workspaces.Item.TimeEntries.Status.InProgress.InProgressRequestBuilder InProgress
        {
            get => new global::ClockifyClient.V1.Workspaces.Item.TimeEntries.Status.InProgress.InProgressRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ClockifyClient.V1.Workspaces.Item.TimeEntries.Status.StatusRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StatusRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/workspaces/{workspaceId}/time-entries/status", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ClockifyClient.V1.Workspaces.Item.TimeEntries.Status.StatusRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StatusRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/workspaces/{workspaceId}/time-entries/status", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
